//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string cloneLinkContent {
            get {
                return ResourceManager.GetString("cloneLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string connect_ClickContent {
            get {
                return ResourceManager.GetString("connect_ClickContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to github.com.
        /// </summary>
        internal static string couldNotConnectToGitHubText {
            get {
                return ResourceManager.GetString("couldNotConnectToGitHubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server..
        /// </summary>
        internal static string couldNotConnectToTheServerText {
            get {
                return ResourceManager.GetString("couldNotConnectToTheServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string createLinkContent {
            get {
                return ResourceManager.GetString("createLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account? .
        /// </summary>
        internal static string dontHaveAnAccountText {
            get {
                return ResourceManager.GetString("dontHaveAnAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have GitHub Enterprise? .
        /// </summary>
        internal static string dontHaveGitHubEnterpriseText {
            get {
                return ResourceManager.GetString("dontHaveGitHubEnterpriseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again..
        /// </summary>
        internal static string dotComConnectionFailedMessageMessage {
            get {
                return ResourceManager.GetString("dotComConnectionFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (forgot your password?).
        /// </summary>
        internal static string dotComForgotPasswordLinkContent {
            get {
                return ResourceManager.GetString("dotComForgotPasswordLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string dotComLogInButtonContent {
            get {
                return ResourceManager.GetString("dotComLogInButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username and password, then try again.
        /// </summary>
        internal static string dotComLoginFailedMessageMessage {
            get {
                return ResourceManager.GetString("dotComLoginFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string dotComPasswordPromptText {
            get {
                return ResourceManager.GetString("dotComPasswordPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        internal static string dotComUserNameOrEmailPromptText {
            get {
                return ResourceManager.GetString("dotComUserNameOrEmailPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host isn&apos;t available or is not a GitHub Enterprise server. Check the address and try again..
        /// </summary>
        internal static string enterpriseConnectingFailedMessage {
            get {
                return ResourceManager.GetString("enterpriseConnectingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string enterpriseLogInButtonContent {
            get {
                return ResourceManager.GetString("enterpriseLogInButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username and password, then try again.
        /// </summary>
        internal static string enterpriseLoginFailedMessageMessage {
            get {
                return ResourceManager.GetString("enterpriseLoginFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string enterprisePasswordPromptText {
            get {
                return ResourceManager.GetString("enterprisePasswordPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Enterprise server address.
        /// </summary>
        internal static string enterpriseUrlPromptText {
            get {
                return ResourceManager.GetString("enterpriseUrlPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        internal static string enterpriseUserNameOrEmailPromptText {
            get {
                return ResourceManager.GetString("enterpriseUserNameOrEmailPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string learnMoreLinkContent {
            get {
                return ResourceManager.GetString("learnMoreLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login_ClickContent {
            get {
                return ResourceManager.GetString("login_ClickContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginContent {
            get {
                return ResourceManager.GetString("loginContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string loginFailedText {
            get {
                return ResourceManager.GetString("loginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string orText {
            get {
                return ResourceManager.GetString("orText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string pricingLinkContent {
            get {
                return ResourceManager.GetString("pricingLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string signOutContent {
            get {
                return ResourceManager.GetString("signOutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string signup_ClickContent {
            get {
                return ResourceManager.GetString("signup_ClickContent", resourceCulture);
            }
        }
    }
}
