//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddedFileStatus {
            get {
                return ResourceManager.GetString("AddedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a containing folder for your new repository..
        /// </summary>
        public static string BrowseForDirectory {
            get {
                return ResourceManager.GetString("BrowseForDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this review? You will lose all your pending comments..
        /// </summary>
        public static string CancelPendingReviewConfirmation {
            get {
                return ResourceManager.GetString("CancelPendingReviewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Review.
        /// </summary>
        public static string CancelPendingReviewConfirmationCaption {
            get {
                return ResourceManager.GetString("CancelPendingReviewConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Requested.
        /// </summary>
        public static string ChangesRequested {
            get {
                return ResourceManager.GetString("ChangesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone a {0} Repository.
        /// </summary>
        public static string CloneTitle {
            get {
                return ResourceManager.GetString("CloneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented.
        /// </summary>
        public static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to github.com.
        /// </summary>
        public static string CouldNotConnectToGitHub {
            get {
                return ResourceManager.GetString("CouldNotConnectToGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Git.exe on PATH.
        ///
        ///Please install Git for Windows from:
        ///https://git-scm.com/download/win.
        /// </summary>
        public static string CouldntFindGitOnPath {
            get {
                return ResourceManager.GetString("CouldntFindGitOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a GitHub Gist.
        /// </summary>
        public static string CreateGistTitle {
            get {
                return ResourceManager.GetString("CreateGistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a {0} Repository.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistFromVisualStudio.cs.
        /// </summary>
        public static string DefaultGistFileName {
            get {
                return ResourceManager.GetString("DefaultGistFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an Enterprise URL.
        /// </summary>
        public static string EnterpriseUrlValidatorEmpty {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Enterprise URL.
        /// </summary>
        public static string EnterpriseUrlValidatorInvalid {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Enterprise server. Please enter an Enterprise URL.
        /// </summary>
        public static string EnterpriseUrlValidatorNotAGitHubHost {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorNotAGitHubHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (forgot your password?).
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fork.
        /// </summary>
        public static string Fork {
            get {
                return ResourceManager.GetString("Fork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork Repository.
        /// </summary>
        public static string ForkRepositoryTitle {
            get {
                return ResourceManager.GetString("ForkRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [invalid].
        /// </summary>
        public static string InvalidBranchName {
            get {
                return ResourceManager.GetString("InvalidBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to use your password and not a Personal Access token to sign in..
        /// </summary>
        public static string LoginFailedForbiddenMessage {
            get {
                return ResourceManager.GetString("LoginFailedForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username and password, then try again.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed..
        /// </summary>
        public static string LoginFailedText {
            get {
                return ResourceManager.GetString("LoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To GitHub.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pull before you can push.
        /// </summary>
        public static string MustPullBeforePush {
            get {
                return ResourceManager.GetString("MustPullBeforePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout PR branch before navigating to Editor.
        /// </summary>
        public static string NavigateToEditorNotCheckedOutInfoMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorNotCheckedOutInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to navigate to Editor (PR branch must be checked out).
        /// </summary>
        public static string NavigateToEditorNotCheckedOutStatusMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorNotCheckedOutStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to navigate to Editor.
        /// </summary>
        public static string NavigateToEditorStatusMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commits to pull.
        /// </summary>
        public static string NoCommitsToPull {
            get {
                return ResourceManager.GetString("NoCommitsToPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commits to push.
        /// </summary>
        public static string NoCommitsToPush {
            get {
                return ResourceManager.GetString("NoCommitsToPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *No description provided.*.
        /// </summary>
        public static string NoDescriptionProvidedMarkdown {
            get {
                return ResourceManager.GetString("NoDescriptionProvidedMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string PasswordValidatorEmpty {
            get {
                return ResourceManager.GetString("PasswordValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request for branch **{0}** created successfully at [{1}]({2}).
        /// </summary>
        public static string PRCreatedUpstream {
            get {
                return ResourceManager.GetString("PRCreatedUpstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish repository.
        /// </summary>
        public static string PublishTitle {
            get {
                return ResourceManager.GetString("PublishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish repository to {0}.
        /// </summary>
        public static string PublishToTitle {
            get {
                return ResourceManager.GetString("PublishToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title for the Pull Request.
        /// </summary>
        public static string PullRequestCreationTitleValidatorEmpty {
            get {
                return ResourceManager.GetString("PullRequestCreationTitleValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout {0}.
        /// </summary>
        public static string PullRequestDetailsCheckout {
            get {
                return ResourceManager.GetString("PullRequestDetailsCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout to {0}.
        /// </summary>
        public static string PullRequestDetailsCheckoutTo {
            get {
                return ResourceManager.GetString("PullRequestDetailsCheckoutTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull from {0} branch {1}.
        /// </summary>
        public static string PullRequestDetailsPullToolTip {
            get {
                return ResourceManager.GetString("PullRequestDetailsPullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to {0} branch {1}.
        /// </summary>
        public static string PullRequestDetailsPushToolTip {
            get {
                return ResourceManager.GetString("PullRequestDetailsPushToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request.
        /// </summary>
        public static string PullRequestNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests.
        /// </summary>
        public static string PullRequestsNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target branch cannot be the same.
        /// </summary>
        public static string PullRequestSourceAndTargetBranchTheSame {
            get {
                return ResourceManager.GetString("PullRequestSourceAndTargetBranchTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source branch doesn&apos;t exist remotely, have you pushed it?.
        /// </summary>
        public static string PullRequestSourceBranchDoesNotExist {
            get {
                return ResourceManager.GetString("PullRequestSourceBranchDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string RenamedFileStatus {
            get {
                return ResourceManager.GetString("RenamedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected repository..
        /// </summary>
        public static string RepositoryCloneFailedNoSelectedRepo {
            get {
                return ResourceManager.GetString("RepositoryCloneFailedNoSelectedRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a repository path.
        /// </summary>
        public static string RepositoryCreationClonePathEmpty {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid path.
        /// </summary>
        public static string RepositoryCreationClonePathInvalid {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path contains invalid characters.
        /// </summary>
        public static string RepositoryCreationClonePathInvalidCharacters {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long.
        /// </summary>
        public static string RepositoryCreationClonePathTooLong {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository &apos;{0}/{1}&apos; already exists..
        /// </summary>
        public static string RepositoryCreationFailedAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the repository name or select a different account and try again..
        /// </summary>
        public static string RepositoryCreationFailedAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded private repositories quota..
        /// </summary>
        public static string RepositoryCreationFailedQuota {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository with same name already exists at this location.
        /// </summary>
        public static string RepositoryNameValidatorAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a repository name.
        /// </summary>
        public static string RepositoryNameValidatorEmpty {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name must be fewer than 100 characters.
        /// </summary>
        public static string RepositoryNameValidatorTooLong {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be created as {0}.
        /// </summary>
        public static string SafeRepositoryNameWarning {
            get {
                return ResourceManager.GetString("SafeRepositoryNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source repository is no longer available..
        /// </summary>
        public static string SourceRepositoryNoLongerAvailable {
            get {
                return ResourceManager.GetString("SourceRepositoryNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Origin.
        /// </summary>
        public static string SwitchOriginTitle {
            get {
                return ResourceManager.GetString("SwitchOriginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync {0} submodules.
        /// </summary>
        public static string SyncSubmodules {
            get {
                return ResourceManager.GetString("SyncSubmodules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the two-factor authentication app on your device to view your authentication code..
        /// </summary>
        public static string TwoFactorApp {
            get {
                return ResourceManager.GetString("TwoFactorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent you a message via SMS with your authentication code..
        /// </summary>
        public static string TwoFactorSms {
            get {
                return ResourceManager.GetString("TwoFactorSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor authentication required.
        /// </summary>
        public static string TwoFactorTitle {
            get {
                return ResourceManager.GetString("TwoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a sign in authentication code here.
        /// </summary>
        public static string TwoFactorUnknown {
            get {
                return ResourceManager.GetString("TwoFactorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username or email address.
        /// </summary>
        public static string UsernameOrEmailValidatorEmpty {
            get {
                return ResourceManager.GetString("UsernameOrEmailValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email address must not have spaces.
        /// </summary>
        public static string UsernameOrEmailValidatorSpaces {
            get {
                return ResourceManager.GetString("UsernameOrEmailValidatorSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot checkout as your working directory has uncommitted changes..
        /// </summary>
        public static string WorkingDirectoryHasUncommittedCHanges {
            get {
                return ResourceManager.GetString("WorkingDirectoryHasUncommittedCHanges", resourceCulture);
            }
        }
    }
}
