//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.App {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 add 的本地化字符串。
        /// </summary>
        public static string AddedFileStatus {
            get {
                return ResourceManager.GetString("AddedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approved 的本地化字符串。
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a containing folder for your new repository. 的本地化字符串。
        /// </summary>
        public static string BrowseForDirectory {
            get {
                return ResourceManager.GetString("BrowseForDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes Requested 的本地化字符串。
        /// </summary>
        public static string ChangesRequested {
            get {
                return ResourceManager.GetString("ChangesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone a {0} Repository 的本地化字符串。
        /// </summary>
        public static string CloneTitle {
            get {
                return ResourceManager.GetString("CloneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commented 的本地化字符串。
        /// </summary>
        public static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not connect to github.com 的本地化字符串。
        /// </summary>
        public static string CouldNotConnectToGitHub {
            get {
                return ResourceManager.GetString("CouldNotConnectToGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t find Git.exe on PATH.
        ///
        ///Please install Git for Windows from:
        ///https://git-scm.com/download/win 的本地化字符串。
        /// </summary>
        public static string CouldntFindGitOnPath {
            get {
                return ResourceManager.GetString("CouldntFindGitOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a GitHub Gist 的本地化字符串。
        /// </summary>
        public static string CreateGistTitle {
            get {
                return ResourceManager.GetString("CreateGistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a {0} Repository 的本地化字符串。
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GistFromVisualStudio.cs 的本地化字符串。
        /// </summary>
        public static string DefaultGistFileName {
            get {
                return ResourceManager.GetString("DefaultGistFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter an Enterprise URL 的本地化字符串。
        /// </summary>
        public static string EnterpriseUrlValidatorEmpty {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid Enterprise URL 的本地化字符串。
        /// </summary>
        public static string EnterpriseUrlValidatorInvalid {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not an Enterprise server. Please enter an Enterprise URL 的本地化字符串。
        /// </summary>
        public static string EnterpriseUrlValidatorNotAGitHubHost {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorNotAGitHubHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (forgot your password?) 的本地化字符串。
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fork 的本地化字符串。
        /// </summary>
        public static string Fork {
            get {
                return ResourceManager.GetString("Fork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fork Repository 的本地化字符串。
        /// </summary>
        public static string ForkRepositoryTitle {
            get {
                return ResourceManager.GetString("ForkRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InProgress 的本地化字符串。
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [invalid] 的本地化字符串。
        /// </summary>
        public static string InvalidBranchName {
            get {
                return ResourceManager.GetString("InvalidBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make sure to use your password and not a Personal Access token to sign in. 的本地化字符串。
        /// </summary>
        public static string LoginFailedForbiddenMessage {
            get {
                return ResourceManager.GetString("LoginFailedForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check your username and password, then try again 的本地化字符串。
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in failed. 的本地化字符串。
        /// </summary>
        public static string LoginFailedText {
            get {
                return ResourceManager.GetString("LoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect To GitHub 的本地化字符串。
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must pull before you can push 的本地化字符串。
        /// </summary>
        public static string MustPullBeforePush {
            get {
                return ResourceManager.GetString("MustPullBeforePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checkout PR branch before navigating to Editor 的本地化字符串。
        /// </summary>
        public static string NavigateToEditorNotCheckedOutInfoMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorNotCheckedOutInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press Enter to navigate to Editor (PR branch must be checked out) 的本地化字符串。
        /// </summary>
        public static string NavigateToEditorNotCheckedOutStatusMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorNotCheckedOutStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press Enter to navigate to Editor 的本地化字符串。
        /// </summary>
        public static string NavigateToEditorStatusMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No commits to pull 的本地化字符串。
        /// </summary>
        public static string NoCommitsToPull {
            get {
                return ResourceManager.GetString("NoCommitsToPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No commits to push 的本地化字符串。
        /// </summary>
        public static string NoCommitsToPush {
            get {
                return ResourceManager.GetString("NoCommitsToPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *No description provided.* 的本地化字符串。
        /// </summary>
        public static string NoDescriptionProvidedMarkdown {
            get {
                return ResourceManager.GetString("NoDescriptionProvidedMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your password 的本地化字符串。
        /// </summary>
        public static string PasswordValidatorEmpty {
            get {
                return ResourceManager.GetString("PasswordValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Request for branch **{0}** created successfully at [{1}]({2}) 的本地化字符串。
        /// </summary>
        public static string PRCreatedUpstream {
            get {
                return ResourceManager.GetString("PRCreatedUpstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish repository 的本地化字符串。
        /// </summary>
        public static string PublishTitle {
            get {
                return ResourceManager.GetString("PublishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish repository to {0} 的本地化字符串。
        /// </summary>
        public static string PublishToTitle {
            get {
                return ResourceManager.GetString("PublishToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a title for the Pull Request 的本地化字符串。
        /// </summary>
        public static string PullRequestCreationTitleValidatorEmpty {
            get {
                return ResourceManager.GetString("PullRequestCreationTitleValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checkout {0} 的本地化字符串。
        /// </summary>
        public static string PullRequestDetailsCheckout {
            get {
                return ResourceManager.GetString("PullRequestDetailsCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checkout to {0} 的本地化字符串。
        /// </summary>
        public static string PullRequestDetailsCheckoutTo {
            get {
                return ResourceManager.GetString("PullRequestDetailsCheckoutTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull from {0} branch {1} 的本地化字符串。
        /// </summary>
        public static string PullRequestDetailsPullToolTip {
            get {
                return ResourceManager.GetString("PullRequestDetailsPullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push to {0} branch {1} 的本地化字符串。
        /// </summary>
        public static string PullRequestDetailsPushToolTip {
            get {
                return ResourceManager.GetString("PullRequestDetailsPushToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Request 的本地化字符串。
        /// </summary>
        public static string PullRequestNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Requests 的本地化字符串。
        /// </summary>
        public static string PullRequestsNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source and target branch cannot be the same 的本地化字符串。
        /// </summary>
        public static string PullRequestSourceAndTargetBranchTheSame {
            get {
                return ResourceManager.GetString("PullRequestSourceAndTargetBranchTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source branch doesn&apos;t exist remotely, have you pushed it? 的本地化字符串。
        /// </summary>
        public static string PullRequestSourceBranchDoesNotExist {
            get {
                return ResourceManager.GetString("PullRequestSourceBranchDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 remote 的本地化字符串。
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rename 的本地化字符串。
        /// </summary>
        public static string RenamedFileStatus {
            get {
                return ResourceManager.GetString("RenamedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No selected repository. 的本地化字符串。
        /// </summary>
        public static string RepositoryCloneFailedNoSelectedRepo {
            get {
                return ResourceManager.GetString("RepositoryCloneFailedNoSelectedRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a repository path 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationClonePathEmpty {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid path 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationClonePathInvalid {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path contains invalid characters 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationClonePathInvalidCharacters {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path too long 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationClonePathTooLong {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository &apos;{0}/{1}&apos; already exists. 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationFailedAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the repository name or select a different account and try again. 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationFailedAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exceeded private repositories quota. 的本地化字符串。
        /// </summary>
        public static string RepositoryCreationFailedQuota {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository with same name already exists at this location 的本地化字符串。
        /// </summary>
        public static string RepositoryNameValidatorAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a repository name 的本地化字符串。
        /// </summary>
        public static string RepositoryNameValidatorEmpty {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository name must be fewer than 100 characters 的本地化字符串。
        /// </summary>
        public static string RepositoryNameValidatorTooLong {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will be created as {0} 的本地化字符串。
        /// </summary>
        public static string SafeRepositoryNameWarning {
            get {
                return ResourceManager.GetString("SafeRepositoryNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source repository is no longer available. 的本地化字符串。
        /// </summary>
        public static string SourceRepositoryNoLongerAvailable {
            get {
                return ResourceManager.GetString("SourceRepositoryNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Origin 的本地化字符串。
        /// </summary>
        public static string SwitchOriginTitle {
            get {
                return ResourceManager.GetString("SwitchOriginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync {0} submodules 的本地化字符串。
        /// </summary>
        public static string SyncSubmodules {
            get {
                return ResourceManager.GetString("SyncSubmodules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the two-factor authentication app on your device to view your authentication code. 的本地化字符串。
        /// </summary>
        public static string TwoFactorApp {
            get {
                return ResourceManager.GetString("TwoFactorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We sent you a message via SMS with your authentication code. 的本地化字符串。
        /// </summary>
        public static string TwoFactorSms {
            get {
                return ResourceManager.GetString("TwoFactorSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two-Factor authentication required 的本地化字符串。
        /// </summary>
        public static string TwoFactorTitle {
            get {
                return ResourceManager.GetString("TwoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a sign in authentication code here 的本地化字符串。
        /// </summary>
        public static string TwoFactorUnknown {
            get {
                return ResourceManager.GetString("TwoFactorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your username or email address 的本地化字符串。
        /// </summary>
        public static string UsernameOrEmailValidatorEmpty {
            get {
                return ResourceManager.GetString("UsernameOrEmailValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or email address must not have spaces 的本地化字符串。
        /// </summary>
        public static string UsernameOrEmailValidatorSpaces {
            get {
                return ResourceManager.GetString("UsernameOrEmailValidatorSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot checkout as your working directory has uncommitted changes. 的本地化字符串。
        /// </summary>
        public static string WorkingDirectoryHasUncommittedCHanges {
            get {
                return ResourceManager.GetString("WorkingDirectoryHasUncommittedCHanges", resourceCulture);
            }
        }
    }
}
