//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.UI.TestAutomation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutomationIDs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationIDs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.UI.TestAutomation.AutomationIDs", typeof(AutomationIDs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountComboBox.
        /// </summary>
        public static string AccountComboBox {
            get {
                return ResourceManager.GetString("AccountComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountListBoxItem.
        /// </summary>
        public static string AccountListBoxItem {
            get {
                return ResourceManager.GetString("AccountListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneAGitHubRepositoryWindow.
        /// </summary>
        public static string CloneAGitHubRepositoryWindow {
            get {
                return ResourceManager.GetString("CloneAGitHubRepositoryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneHyperlink.
        /// </summary>
        public static string CloneHyperlink {
            get {
                return ResourceManager.GetString("CloneHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneRepositoryButton.
        /// </summary>
        public static string CloneRepositoryButton {
            get {
                return ResourceManager.GetString("CloneRepositoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneRepositoryCloseButton.
        /// </summary>
        public static string CloneRepositoryCloseButton {
            get {
                return ResourceManager.GetString("CloneRepositoryCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneRepositoryLocalPathBrowsePathButton.
        /// </summary>
        public static string CloneRepositoryLocalPathBrowsePathButton {
            get {
                return ResourceManager.GetString("CloneRepositoryLocalPathBrowsePathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneRepositoryLocalPathCustom.
        /// </summary>
        public static string CloneRepositoryLocalPathCustom {
            get {
                return ResourceManager.GetString("CloneRepositoryLocalPathCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneRepositoryTitleBar.
        /// </summary>
        public static string CloneRepositoryTitleBar {
            get {
                return ResourceManager.GetString("CloneRepositoryTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectToGitHubCloseButton.
        /// </summary>
        public static string ConnectToGitHubCloseButton {
            get {
                return ResourceManager.GetString("ConnectToGitHubCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectToGitHubMenuItem.
        /// </summary>
        public static string ConnectToGitHubMenuItem {
            get {
                return ResourceManager.GetString("ConnectToGitHubMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectToGitHubTitleBar.
        /// </summary>
        public static string ConnectToGitHubTitleBar {
            get {
                return ResourceManager.GetString("ConnectToGitHubTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectToGitHubWindow.
        /// </summary>
        public static string ConnectToGitHubWindow {
            get {
                return ResourceManager.GetString("ConnectToGitHubWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAGitHubGistControl.
        /// </summary>
        public static string CreateAGitHubGistControl {
            get {
                return ResourceManager.GetString("CreateAGitHubGistControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAGitHubGistTitleBar.
        /// </summary>
        public static string CreateAGitHubGistTitleBar {
            get {
                return ResourceManager.GetString("CreateAGitHubGistTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAGitHubRepositoryWindow.
        /// </summary>
        public static string CreateAGitHubRepositoryWindow {
            get {
                return ResourceManager.GetString("CreateAGitHubRepositoryWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedPullRequestAuthorImage.
        /// </summary>
        public static string CreatedPullRequestAuthorImage {
            get {
                return ResourceManager.GetString("CreatedPullRequestAuthorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedPullRequestDetailsTextBlock.
        /// </summary>
        public static string CreatedPullRequestDetailsTextBlock {
            get {
                return ResourceManager.GetString("CreatedPullRequestDetailsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedPullRequestListItem.
        /// </summary>
        public static string CreatedPullRequestListItem {
            get {
                return ResourceManager.GetString("CreatedPullRequestListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedPullRequestNumberHyperlink.
        /// </summary>
        public static string CreatedPullRequestNumberHyperlink {
            get {
                return ResourceManager.GetString("CreatedPullRequestNumberHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedPullRequestTitleHyperlink.
        /// </summary>
        public static string CreatedPullRequestTitleHyperlink {
            get {
                return ResourceManager.GetString("CreatedPullRequestTitleHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateGistButton.
        /// </summary>
        public static string CreateGistButton {
            get {
                return ResourceManager.GetString("CreateGistButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateHyperlink.
        /// </summary>
        public static string CreateHyperlink {
            get {
                return ResourceManager.GetString("CreateHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewHyperlink.
        /// </summary>
        public static string CreateNewHyperlink {
            get {
                return ResourceManager.GetString("CreateNewHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRepositoryButton.
        /// </summary>
        public static string CreateRepositoryButton {
            get {
                return ResourceManager.GetString("CreateRepositoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRepositoryCloseButton.
        /// </summary>
        public static string CreateRepositoryCloseButton {
            get {
                return ResourceManager.GetString("CreateRepositoryCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRepositoryLocalPathBrowseButton.
        /// </summary>
        public static string CreateRepositoryLocalPathBrowseButton {
            get {
                return ResourceManager.GetString("CreateRepositoryLocalPathBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRepositoryLocalPathTextBox.
        /// </summary>
        public static string CreateRepositoryLocalPathTextBox {
            get {
                return ResourceManager.GetString("CreateRepositoryLocalPathTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRepositoryTitleBar.
        /// </summary>
        public static string CreateRepositoryTitleBar {
            get {
                return ResourceManager.GetString("CreateRepositoryTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DontHaveDotcomAccountTextBlock.
        /// </summary>
        public static string DontHaveDotcomAccountTextBlock {
            get {
                return ResourceManager.GetString("DontHaveDotcomAccountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DontHaveEnterpriseTextBlock.
        /// </summary>
        public static string DontHaveEnterpriseTextBlock {
            get {
                return ResourceManager.GetString("DontHaveEnterpriseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotcomPasswordTextBox.
        /// </summary>
        public static string DotcomPasswordTextBox {
            get {
                return ResourceManager.GetString("DotcomPasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotcomSignInButton.
        /// </summary>
        public static string DotcomSignInButton {
            get {
                return ResourceManager.GetString("DotcomSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotcomSignUpHyperlink.
        /// </summary>
        public static string DotcomSignUpHyperlink {
            get {
                return ResourceManager.GetString("DotcomSignUpHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotcomUsernameEmailTextBox.
        /// </summary>
        public static string DotcomUsernameEmailTextBox {
            get {
                return ResourceManager.GetString("DotcomUsernameEmailTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterpriseLearnMoreHyperlink.
        /// </summary>
        public static string EnterpriseLearnMoreHyperlink {
            get {
                return ResourceManager.GetString("EnterpriseLearnMoreHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterprisePasswordTextBox.
        /// </summary>
        public static string EnterprisePasswordTextBox {
            get {
                return ResourceManager.GetString("EnterprisePasswordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterpriseServerAddressTextBox.
        /// </summary>
        public static string EnterpriseServerAddressTextBox {
            get {
                return ResourceManager.GetString("EnterpriseServerAddressTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterpriseSignInButton.
        /// </summary>
        public static string EnterpriseSignInButton {
            get {
                return ResourceManager.GetString("EnterpriseSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterpriseUsernameEmailTextBox.
        /// </summary>
        public static string EnterpriseUsernameEmailTextBox {
            get {
                return ResourceManager.GetString("EnterpriseUsernameEmailTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistAccountImage.
        /// </summary>
        public static string GistAccountImage {
            get {
                return ResourceManager.GetString("GistAccountImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistAccountNameTextBlock.
        /// </summary>
        public static string GistAccountNameTextBlock {
            get {
                return ResourceManager.GetString("GistAccountNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistCreationControlCustom.
        /// </summary>
        public static string GistCreationControlCustom {
            get {
                return ResourceManager.GetString("GistCreationControlCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistDescriptionTextBlock.
        /// </summary>
        public static string GistDescriptionTextBlock {
            get {
                return ResourceManager.GetString("GistDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistDescriptionTextBox.
        /// </summary>
        public static string GistDescriptionTextBox {
            get {
                return ResourceManager.GetString("GistDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistErrorMessageTextBlock.
        /// </summary>
        public static string GistErrorMessageTextBlock {
            get {
                return ResourceManager.GetString("GistErrorMessageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistFileNameTextBlock.
        /// </summary>
        public static string GistFileNameTextBlock {
            get {
                return ResourceManager.GetString("GistFileNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistFileNameTextBox.
        /// </summary>
        public static string GistFileNameTextBox {
            get {
                return ResourceManager.GetString("GistFileNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubConnectContentCustom.
        /// </summary>
        public static string GitHubConnectContentCustom {
            get {
                return ResourceManager.GetString("GitHubConnectContentCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubHomeContentCustom.
        /// </summary>
        public static string GitHubHomeContentCustom {
            get {
                return ResourceManager.GetString("GitHubHomeContentCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubInfoPanel.
        /// </summary>
        public static string GitHubInfoPanel {
            get {
                return ResourceManager.GetString("GitHubInfoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubInfoPanelCancelButton.
        /// </summary>
        public static string GitHubInfoPanelCancelButton {
            get {
                return ResourceManager.GetString("GitHubInfoPanelCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubInfoPanelMessageDocument.
        /// </summary>
        public static string GitHubInfoPanelMessageDocument {
            get {
                return ResourceManager.GetString("GitHubInfoPanelMessageDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubLoggedOutCreateAnAccountHyperlink.
        /// </summary>
        public static string GitHubLoggedOutCreateAnAccountHyperlink {
            get {
                return ResourceManager.GetString("GitHubLoggedOutCreateAnAccountHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubLoggedOutSignInHyperlink.
        /// </summary>
        public static string GitHubLoggedOutSignInHyperlink {
            get {
                return ResourceManager.GetString("GitHubLoggedOutSignInHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubPaneView.
        /// </summary>
        public static string GitHubPaneView {
            get {
                return ResourceManager.GetString("GitHubPaneView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubTabItem.
        /// </summary>
        public static string GitHubTabItem {
            get {
                return ResourceManager.GetString("GitHubTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBar.
        /// </summary>
        public static string GitHubToolBar {
            get {
                return ResourceManager.GetString("GitHubToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarBackImage.
        /// </summary>
        public static string GitHubToolBarBackImage {
            get {
                return ResourceManager.GetString("GitHubToolBarBackImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarForwardImage.
        /// </summary>
        public static string GitHubToolBarForwardImage {
            get {
                return ResourceManager.GetString("GitHubToolBarForwardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarPullRequestImage.
        /// </summary>
        public static string GitHubToolBarPullRequestImage {
            get {
                return ResourceManager.GetString("GitHubToolBarPullRequestImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubToolBarRefreshImage.
        /// </summary>
        public static string GitHubToolBarRefreshImage {
            get {
                return ResourceManager.GetString("GitHubToolBarRefreshImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitignoreComboBox.
        /// </summary>
        public static string GitignoreComboBox {
            get {
                return ResourceManager.GetString("GitignoreComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitignoreFilterTextBox.
        /// </summary>
        public static string GitignoreFilterTextBox {
            get {
                return ResourceManager.GetString("GitignoreFilterTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitignoreListBoxItem.
        /// </summary>
        public static string GitignoreListBoxItem {
            get {
                return ResourceManager.GetString("GitignoreListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitignorePopupWindow.
        /// </summary>
        public static string GitignorePopupWindow {
            get {
                return ResourceManager.GetString("GitignorePopupWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitignoreTextBlock.
        /// </summary>
        public static string GitignoreTextBlock {
            get {
                return ResourceManager.GetString("GitignoreTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseComboBox.
        /// </summary>
        public static string LicenseComboBox {
            get {
                return ResourceManager.GetString("LicenseComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseFilterTextBox.
        /// </summary>
        public static string LicenseFilterTextBox {
            get {
                return ResourceManager.GetString("LicenseFilterTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseListBoxItem.
        /// </summary>
        public static string LicenseListBoxItem {
            get {
                return ResourceManager.GetString("LicenseListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicensePopupWindow.
        /// </summary>
        public static string LicensePopupWindow {
            get {
                return ResourceManager.GetString("LicensePopupWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseTextBlock.
        /// </summary>
        public static string LicenseTextBlock {
            get {
                return ResourceManager.GetString("LicenseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggedOutViewCustom.
        /// </summary>
        public static string LoggedOutViewCustom {
            get {
                return ResourceManager.GetString("LoggedOutViewCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerfulCollaborationTextBlock.
        /// </summary>
        public static string PowerfulCollaborationTextBlock {
            get {
                return ResourceManager.GetString("PowerfulCollaborationTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateGistCheckBox.
        /// </summary>
        public static string PrivateGistCheckBox {
            get {
                return ResourceManager.GetString("PrivateGistCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateRepositoryCheckBox.
        /// </summary>
        public static string PrivateRepositoryCheckBox {
            get {
                return ResourceManager.GetString("PrivateRepositoryCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationCancelButton.
        /// </summary>
        public static string PullRequestCreationCancelButton {
            get {
                return ResourceManager.GetString("PullRequestCreationCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationCreateButton.
        /// </summary>
        public static string PullRequestCreationCreateButton {
            get {
                return ResourceManager.GetString("PullRequestCreationCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationDescriptionTextBox.
        /// </summary>
        public static string PullRequestCreationDescriptionTextBox {
            get {
                return ResourceManager.GetString("PullRequestCreationDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationDetailPane.
        /// </summary>
        public static string PullRequestCreationDetailPane {
            get {
                return ResourceManager.GetString("PullRequestCreationDetailPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationTitleTextBox.
        /// </summary>
        public static string PullRequestCreationTitleTextBox {
            get {
                return ResourceManager.GetString("PullRequestCreationTitleTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestCreationViewCustom.
        /// </summary>
        public static string PullRequestCreationViewCustom {
            get {
                return ResourceManager.GetString("PullRequestCreationViewCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListAssigneeFilterComboBox.
        /// </summary>
        public static string PullRequestListAssigneeFilterComboBox {
            get {
                return ResourceManager.GetString("PullRequestListAssigneeFilterComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListAuthorFilterComboBox.
        /// </summary>
        public static string PullRequestListAuthorFilterComboBox {
            get {
                return ResourceManager.GetString("PullRequestListAuthorFilterComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListFilterAssigneesDropDown.
        /// </summary>
        public static string PullRequestListFilterAssigneesDropDown {
            get {
                return ResourceManager.GetString("PullRequestListFilterAssigneesDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListStatusFilterComboBox.
        /// </summary>
        public static string PullRequestListStatusFilterComboBox {
            get {
                return ResourceManager.GetString("PullRequestListStatusFilterComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestListViewCustom.
        /// </summary>
        public static string PullRequestListViewCustom {
            get {
                return ResourceManager.GetString("PullRequestListViewCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestRepositoryNameTextBlock.
        /// </summary>
        public static string PullRequestRepositoryNameTextBlock {
            get {
                return ResourceManager.GetString("PullRequestRepositoryNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestSourceBranchHyperlink.
        /// </summary>
        public static string PullRequestSourceBranchHyperlink {
            get {
                return ResourceManager.GetString("PullRequestSourceBranchHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PullRequestTargetBranchComboBox.
        /// </summary>
        public static string PullRequestTargetBranchComboBox {
            get {
                return ResourceManager.GetString("PullRequestTargetBranchComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryCloneControlCustom.
        /// </summary>
        public static string RepositoryCloneControlCustom {
            get {
                return ResourceManager.GetString("RepositoryCloneControlCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryCreationControlCustom.
        /// </summary>
        public static string RepositoryCreationControlCustom {
            get {
                return ResourceManager.GetString("RepositoryCreationControlCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryDescriptionTextBlock.
        /// </summary>
        public static string RepositoryDescriptionTextBlock {
            get {
                return ResourceManager.GetString("RepositoryDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryDescriptionTextBox.
        /// </summary>
        public static string RepositoryDescriptionTextBox {
            get {
                return ResourceManager.GetString("RepositoryDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryGroupItem.
        /// </summary>
        public static string RepositoryGroupItem {
            get {
                return ResourceManager.GetString("RepositoryGroupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryListBoxItem.
        /// </summary>
        public static string RepositoryListBoxItem {
            get {
                return ResourceManager.GetString("RepositoryListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryNameTextBlock.
        /// </summary>
        public static string RepositoryNameTextBlock {
            get {
                return ResourceManager.GetString("RepositoryNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryNameTextBox.
        /// </summary>
        public static string RepositoryNameTextBox {
            get {
                return ResourceManager.GetString("RepositoryNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchRepositoryTextBox.
        /// </summary>
        public static string SearchRepositoryTextBox {
            get {
                return ResourceManager.GetString("SearchRepositoryTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectABranchComboBox.
        /// </summary>
        public static string SelectABranchComboBox {
            get {
                return ResourceManager.GetString("SelectABranchComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInCustom.
        /// </summary>
        public static string SignInCustom {
            get {
                return ResourceManager.GetString("SignInCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInDotcomHostTabItem.
        /// </summary>
        public static string SignInDotcomHostTabItem {
            get {
                return ResourceManager.GetString("SignInDotcomHostTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInEnterpriseHostTabItem.
        /// </summary>
        public static string SignInEnterpriseHostTabItem {
            get {
                return ResourceManager.GetString("SignInEnterpriseHostTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInHostTab.
        /// </summary>
        public static string SignInHostTab {
            get {
                return ResourceManager.GetString("SignInHostTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInHyperlink.
        /// </summary>
        public static string SignInHyperlink {
            get {
                return ResourceManager.GetString("SignInHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignInToGitHubTextBlock.
        /// </summary>
        public static string SignInToGitHubTextBlock {
            get {
                return ResourceManager.GetString("SignInToGitHubTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOutHyperlink.
        /// </summary>
        public static string SignOutHyperlink {
            get {
                return ResourceManager.GetString("SignOutHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerConnectGitHubSectionButton.
        /// </summary>
        public static string TeamExplorerConnectGitHubSectionButton {
            get {
                return ResourceManager.GetString("TeamExplorerConnectGitHubSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerConnectGitHubSectionTextBlock.
        /// </summary>
        public static string TeamExplorerConnectGitHubSectionTextBlock {
            get {
                return ResourceManager.GetString("TeamExplorerConnectGitHubSectionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerHomeGitHubSectionButton.
        /// </summary>
        public static string TeamExplorerHomeGitHubSectionButton {
            get {
                return ResourceManager.GetString("TeamExplorerHomeGitHubSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerHomeGitHubSectionTextBlock.
        /// </summary>
        public static string TeamExplorerHomeGitHubSectionTextBlock {
            get {
                return ResourceManager.GetString("TeamExplorerHomeGitHubSectionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerPrivateRepositoryCheckBox.
        /// </summary>
        public static string TeamExplorerPrivateRepositoryCheckBox {
            get {
                return ResourceManager.GetString("TeamExplorerPrivateRepositoryCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerPublishAccountComboBox.
        /// </summary>
        public static string TeamExplorerPublishAccountComboBox {
            get {
                return ResourceManager.GetString("TeamExplorerPublishAccountComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerPublishHostComboBox.
        /// </summary>
        public static string TeamExplorerPublishHostComboBox {
            get {
                return ResourceManager.GetString("TeamExplorerPublishHostComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerPublishRepositoryButton.
        /// </summary>
        public static string TeamExplorerPublishRepositoryButton {
            get {
                return ResourceManager.GetString("TeamExplorerPublishRepositoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerPublishRepositoryDescriptionTextBox.
        /// </summary>
        public static string TeamExplorerPublishRepositoryDescriptionTextBox {
            get {
                return ResourceManager.GetString("TeamExplorerPublishRepositoryDescriptionTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerPublishRepositoryNameTextBox.
        /// </summary>
        public static string TeamExplorerPublishRepositoryNameTextBox {
            get {
                return ResourceManager.GetString("TeamExplorerPublishRepositoryNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerRepositoryListBoxItem.
        /// </summary>
        public static string TeamExplorerRepositoryListBoxItem {
            get {
                return ResourceManager.GetString("TeamExplorerRepositoryListBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerRepositoryListView.
        /// </summary>
        public static string TeamExplorerRepositoryListView {
            get {
                return ResourceManager.GetString("TeamExplorerRepositoryListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerRepositoryNameTextBlock.
        /// </summary>
        public static string TeamExplorerRepositoryNameTextBlock {
            get {
                return ResourceManager.GetString("TeamExplorerRepositoryNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerRepositoryURLTextBlock.
        /// </summary>
        public static string TeamExplorerRepositoryURLTextBlock {
            get {
                return ResourceManager.GetString("TeamExplorerRepositoryURLTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerSyncGitHubRepositoryPublishCustom.
        /// </summary>
        public static string TeamExplorerSyncGitHubRepositoryPublishCustom {
            get {
                return ResourceManager.GetString("TeamExplorerSyncGitHubRepositoryPublishCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerSyncGitHubSectionButton.
        /// </summary>
        public static string TeamExplorerSyncGitHubSectionButton {
            get {
                return ResourceManager.GetString("TeamExplorerSyncGitHubSectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamExplorerSyncGitHubSectionTextBlock.
        /// </summary>
        public static string TeamExplorerSyncGitHubSectionTextBlock {
            get {
                return ResourceManager.GetString("TeamExplorerSyncGitHubSectionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationCloseButton.
        /// </summary>
        public static string TwoFactorAuthenticationCloseButton {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationCustom.
        /// </summary>
        public static string TwoFactorAuthenticationCustom {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationInformationTextBlock.
        /// </summary>
        public static string TwoFactorAuthenticationInformationTextBlock {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationInformationTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationInputStackPanel.
        /// </summary>
        public static string TwoFactorAuthenticationInputStackPanel {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationInputStackPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationLearnMoreHyperlink.
        /// </summary>
        public static string TwoFactorAuthenticationLearnMoreHyperlink {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationLearnMoreHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationTitleBar.
        /// </summary>
        public static string TwoFactorAuthenticationTitleBar {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticationWindow.
        /// </summary>
        public static string TwoFactorAuthenticationWindow {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticatonInputCustom.
        /// </summary>
        public static string TwoFactorAuthenticatonInputCustom {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticatonInputCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwoFactorAuthenticatonVerifyButton.
        /// </summary>
        public static string TwoFactorAuthenticatonVerifyButton {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticatonVerifyButton", resourceCulture);
            }
        }
    }
}
