// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHub.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGitHubEssentialsPkgString = "c3a2c467-6b73-4909-8ce7-12a456ea77d7";
        public static Guid guidGitHubEssentialsPkg = new Guid(guidGitHubEssentialsPkgString);

        public const string guidGitHubEssentialsCmdSetString = "8de10943-8643-4f81-88a3-83b81d204ff4";
        public static Guid guidGitHubEssentialsCmdSet = new Guid(guidGitHubEssentialsCmdSetString);

        public const string guidManageConnectionsString = "0a014553-a0aa-46dd-8d6b-b8e3178ca435";
        public static Guid guidManageConnections = new Guid(guidManageConnectionsString);

        public const string guidImagesString = "de556d01-f3bc-4521-abc3-3e04b537f9c9";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int addConnectionCommand = 0x0110;
        public const int idGitHubMenuGroup = 0x1020;
        public const int idManageConnections = 0x1009;
        public const int logo = 0x0001;
    }
}