//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.VisualStudio.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.VisualStudio.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review comment.
        /// </summary>
        public static string AddReviewComment {
            get {
                return ResourceManager.GetString("AddReviewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a single comment.
        /// </summary>
        public static string AddSingleComment {
            get {
                return ResourceManager.GetString("AddSingleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your review.
        /// </summary>
        public static string AddYourReview {
            get {
                return ResourceManager.GetString("AddYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication code.
        /// </summary>
        public static string authenticationFailedLabelContent {
            get {
                return ResourceManager.GetString("authenticationFailedLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try entering the code again or clicking the resend button to get a new authentication code..
        /// </summary>
        public static string authenticationFailedLabelMessage {
            get {
                return ResourceManager.GetString("authenticationFailedLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication code sent!.
        /// </summary>
        public static string authenticationSentLabelContent {
            get {
                return ResourceManager.GetString("authenticationSentLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not receive the authentication code, contact support@github.com..
        /// </summary>
        public static string authenticationSentLabelMessage {
            get {
                return ResourceManager.GetString("authenticationSentLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GitHub extension is not available inside Blend.
        /// </summary>
        public static string BlendDialogText {
            get {
                return ResourceManager.GetString("BlendDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful collaboration, code review, and code management for open source and private projects..
        /// </summary>
        public static string BlurbText {
            get {
                return ResourceManager.GetString("BlurbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browsePathButtonContent {
            get {
                return ResourceManager.GetString("browsePathButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLink {
            get {
                return ResourceManager.GetString("CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes ({0}).
        /// </summary>
        public static string ChangesCountFormat {
            get {
                return ResourceManager.GetString("ChangesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string CloneLink {
            get {
                return ResourceManager.GetString("CloneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare File as Default Action.
        /// </summary>
        public static string CompareFileAsDefaultAction {
            get {
                return ResourceManager.GetString("CompareFileAsDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue your review.
        /// </summary>
        public static string ContinueYourReview {
            get {
                return ResourceManager.GetString("ContinueYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to github.com.
        /// </summary>
        public static string couldNotConnectToGitHubText {
            get {
                return ResourceManager.GetString("couldNotConnectToGitHubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server..
        /// </summary>
        public static string couldNotConnectToTheServerText {
            get {
                return ResourceManager.GetString("couldNotConnectToTheServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string CreateAccountLink {
            get {
                return ResourceManager.GetString("CreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        public static string DeleteCommentConfirmation {
            get {
                return ResourceManager.GetString("DeleteCommentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        public static string DeleteCommentConfirmationCaption {
            get {
                return ResourceManager.GetString("DeleteCommentConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Optional).
        /// </summary>
        public static string DescriptionOptional {
            get {
                return ResourceManager.GetString("DescriptionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account? .
        /// </summary>
        public static string dontHaveAnAccountText {
            get {
                return ResourceManager.GetString("dontHaveAnAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have GitHub Enterprise? .
        /// </summary>
        public static string dontHaveGitHubEnterpriseText {
            get {
                return ResourceManager.GetString("dontHaveGitHubEnterpriseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again..
        /// </summary>
        public static string dotComConnectionFailedMessageMessage {
            get {
                return ResourceManager.GetString("dotComConnectionFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host isn&apos;t available or is not a GitHub Enterprise server. Check the address and try again..
        /// </summary>
        public static string enterpriseConnectingFailedMessage {
            get {
                return ResourceManager.GetString("enterpriseConnectingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Enterprise server address.
        /// </summary>
        public static string enterpriseUrlPromptText {
            get {
                return ResourceManager.GetString("enterpriseUrlPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy to the clipboard. Please try again..
        /// </summary>
        public static string Error_FailedToCopyToClipboard {
            get {
                return ResourceManager.GetString("Error_FailedToCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string fileNameText {
            get {
                return ResourceManager.GetString("fileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter branches.
        /// </summary>
        public static string filterBranchesText {
            get {
                return ResourceManager.GetString("filterBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search repositories.
        /// </summary>
        public static string filterTextPromptText {
            get {
                return ResourceManager.GetString("filterTextPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (forgot your password?).
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork.
        /// </summary>
        public static string ForkNavigationItemText {
            get {
                return ResourceManager.GetString("ForkNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStartedText {
            get {
                return ResourceManager.GetString("GetStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gist created.
        /// </summary>
        public static string gistCreatedMessage {
            get {
                return ResourceManager.GetString("gistCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create gist.
        /// </summary>
        public static string gistCreationFailedMessage {
            get {
                return ResourceManager.GetString("gistCreationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect….
        /// </summary>
        public static string GitHubInvitationSectionConnectLabel {
            get {
                return ResourceManager.GetString("GitHubInvitationSectionConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to GitHub.
        /// </summary>
        public static string GitHubPublishSectionTitle {
            get {
                return ResourceManager.GetString("GitHubPublishSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string GraphsNavigationItemText {
            get {
                return ResourceManager.GetString("GraphsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git ignore.
        /// </summary>
        public static string ignoreTemplateListText {
            get {
                return ResourceManager.GetString("ignoreTemplateListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string IssuesNavigationItemText {
            get {
                return ResourceManager.GetString("IssuesNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string learnMoreLink {
            get {
                return ResourceManager.GetString("learnMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string licenseListText {
            get {
                return ResourceManager.GetString("licenseListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied to clipboard.
        /// </summary>
        public static string LinkCopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some or all repositories may not have loaded. Close the dialog and try again..
        /// </summary>
        public static string loadingFailedMessageContent {
            get {
                return ResourceManager.GetString("loadingFailedMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading repositories.
        /// </summary>
        public static string loadingFailedMessageMessage {
            get {
                return ResourceManager.GetString("loadingFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local branch up to date.
        /// </summary>
        public static string LocalBranchUpToDate {
            get {
                return ResourceManager.GetString("LocalBranchUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path.
        /// </summary>
        public static string localPathText {
            get {
                return ResourceManager.GetString("localPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username and password, then try again.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed..
        /// </summary>
        public static string LoginFailedText {
            get {
                return ResourceManager.GetString("LoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Repository.
        /// </summary>
        public static string makePrivateContent {
            get {
                return ResourceManager.GetString("makePrivateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Gist.
        /// </summary>
        public static string makePrivateGist {
            get {
                return ResourceManager.GetString("makePrivateGist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nameText {
            get {
                return ResourceManager.GetString("nameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repositories.
        /// </summary>
        public static string noRepositoriesMessageText {
            get {
                return ResourceManager.GetString("noRepositoriesMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This repository is not on GitHub.
        /// </summary>
        public static string NotAGitHubRepository {
            get {
                return ResourceManager.GetString("NotAGitHubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish this repository to GitHub and get powerful collaboration, code review, and code management for open source and private projects..
        /// </summary>
        public static string NotAGitHubRepositoryMessage {
            get {
                return ResourceManager.GetString("NotAGitHubRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository.
        /// </summary>
        public static string NotAGitRepository {
            get {
                return ResourceManager.GetString("NotAGitRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a git repository here. Open a git project or click &quot;File -&gt; Add to Source Control&quot; in a project to get started..
        /// </summary>
        public static string NotAGitRepositoryMessage {
            get {
                return ResourceManager.GetString("NotAGitRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in to {0}, so certain git operations may fail. [Sign in now]({1}).
        /// </summary>
        public static string NotLoggedInMessage {
            get {
                return ResourceManager.GetString("NotLoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File as Default Action.
        /// </summary>
        public static string OpenFileAsDefaultAction {
            get {
                return ResourceManager.GetString("OpenFileAsDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File in Solution.
        /// </summary>
        public static string OpenFileInSolution {
            get {
                return ResourceManager.GetString("OpenFileInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string openInBrowser {
            get {
                return ResourceManager.GetString("openInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pull Request on GitHub.
        /// </summary>
        public static string OpenPROnGitHubToolTip {
            get {
                return ResourceManager.GetString("OpenPROnGitHubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the two-factor authentication app on your device to view your authentication code..
        /// </summary>
        public static string openTwoFactorAuthAppText {
            get {
                return ResourceManager.GetString("openTwoFactorAuthAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string Options_DebuggingTitle {
            get {
                return ResourceManager.GetString("Options_DebuggingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PR comments on editor margin.
        /// </summary>
        public static string Options_EditorCommentsLabel {
            get {
                return ResourceManager.GetString("Options_EditorCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Trace Logging.
        /// </summary>
        public static string Options_EnableTraceLoggingText {
            get {
                return ResourceManager.GetString("Options_EnableTraceLoggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These features might change in a future version.
        /// </summary>
        public static string Options_ExperimentalNote {
            get {
                return ResourceManager.GetString("Options_ExperimentalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental features.
        /// </summary>
        public static string Options_ExperimentalTitle {
            get {
                return ResourceManager.GetString("Options_ExperimentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Fork button in Team Explorer.
        /// </summary>
        public static string Options_ForkButtonLabel {
            get {
                return ResourceManager.GetString("Options_ForkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve by sending anonymous usage data.
        /// </summary>
        public static string Options_MetricsLabel {
            get {
                return ResourceManager.GetString("Options_MetricsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Options_PrivacyTitle {
            get {
                return ResourceManager.GetString("Options_PrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string orText {
            get {
                return ResourceManager.GetString("orText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string pathText {
            get {
                return ResourceManager.GetString("pathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string prUpdatedByText {
            get {
                return ResourceManager.GetString("prUpdatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string prUpdatedText {
            get {
                return ResourceManager.GetString("prUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string publishText {
            get {
                return ResourceManager.GetString("publishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to GitHub.
        /// </summary>
        public static string PublishToGitHubButton {
            get {
                return ResourceManager.GetString("PublishToGitHubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests.
        /// </summary>
        public static string PullRequestsNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string PulseNavigationItemText {
            get {
                return ResourceManager.GetString("PulseNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This repository does not have a remote. Fill out the form to publish it to GitHub..
        /// </summary>
        public static string RepoDoesNotHaveRemoteText {
            get {
                return ResourceManager.GetString("RepoDoesNotHaveRemoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Name.
        /// </summary>
        public static string RepoNameText {
            get {
                return ResourceManager.GetString("RepoNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository created successfully..
        /// </summary>
        public static string RepositoryPublishedMessage {
            get {
                return ResourceManager.GetString("RepositoryPublishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string resendCodeButtonContent {
            get {
                return ResourceManager.GetString("resendCodeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the code to your registered SMS Device again.
        /// </summary>
        public static string resendCodeButtonToolTip {
            get {
                return ResourceManager.GetString("resendCodeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewers.
        /// </summary>
        public static string Reviewers {
            get {
                return ResourceManager.GetString("Reviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in....
        /// </summary>
        public static string SignInCallToAction {
            get {
                return ResourceManager.GetString("SignInCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInLink {
            get {
                return ResourceManager.GetString("SignInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutLink {
            get {
                return ResourceManager.GetString("SignOutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpLink {
            get {
                return ResourceManager.GetString("SignUpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to List View.
        /// </summary>
        public static string SwitchToListView {
            get {
                return ResourceManager.GetString("SwitchToListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Tree View.
        /// </summary>
        public static string SwitchToTreeView {
            get {
                return ResourceManager.GetString("SwitchToTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to GitHub for Visual Studio! Why not take a look at our [training](show-training) or [documentation](show-docs)?
        ///
        ///[Don&apos;t show this again](dont-show-again).
        /// </summary>
        public static string TeamExplorerWelcomeMessage {
            get {
                return ResourceManager.GetString("TeamExplorerWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (required).
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string TokenPrompt {
            get {
                return ResourceManager.GetString("TokenPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string twoFactorAuthText {
            get {
                return ResourceManager.GetString("twoFactorAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update comment.
        /// </summary>
        public static string UpdateComment {
            get {
                return ResourceManager.GetString("UpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated {0}.
        /// </summary>
        public static string UpdatedFormat {
            get {
                return ResourceManager.GetString("UpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string UserNameOrEmailPromptText {
            get {
                return ResourceManager.GetString("UserNameOrEmailPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string verifyText {
            get {
                return ResourceManager.GetString("verifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changes.
        /// </summary>
        public static string ViewChanges {
            get {
                return ResourceManager.GetString("ViewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changes in Solution.
        /// </summary>
        public static string ViewChangesInSolution {
            get {
                return ResourceManager.GetString("ViewChangesInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View File.
        /// </summary>
        public static string ViewFile {
            get {
                return ResourceManager.GetString("ViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string WikiNavigationItemText {
            get {
                return ResourceManager.GetString("WikiNavigationItemText", resourceCulture);
            }
        }
    }
}
