//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.VisualStudio.UI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.VisualStudio.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add review comment 的本地化字符串。
        /// </summary>
        public static string AddReviewComment {
            get {
                return ResourceManager.GetString("AddReviewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a single comment 的本地化字符串。
        /// </summary>
        public static string AddSingleComment {
            get {
                return ResourceManager.GetString("AddSingleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add your review 的本地化字符串。
        /// </summary>
        public static string AddYourReview {
            get {
                return ResourceManager.GetString("AddYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid authentication code 的本地化字符串。
        /// </summary>
        public static string authenticationFailedLabelContent {
            get {
                return ResourceManager.GetString("authenticationFailedLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try entering the code again or clicking the resend button to get a new authentication code. 的本地化字符串。
        /// </summary>
        public static string authenticationFailedLabelMessage {
            get {
                return ResourceManager.GetString("authenticationFailedLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication code sent! 的本地化字符串。
        /// </summary>
        public static string authenticationSentLabelContent {
            get {
                return ResourceManager.GetString("authenticationSentLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you do not receive the authentication code, contact support@github.com. 的本地化字符串。
        /// </summary>
        public static string authenticationSentLabelMessage {
            get {
                return ResourceManager.GetString("authenticationSentLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The GitHub extension is not available inside Blend 的本地化字符串。
        /// </summary>
        public static string BlendDialogText {
            get {
                return ResourceManager.GetString("BlendDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powerful collaboration, code review, and code management for open source and private projects. 的本地化字符串。
        /// </summary>
        public static string BlurbText {
            get {
                return ResourceManager.GetString("BlurbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string browsePathButtonContent {
            get {
                return ResourceManager.GetString("browsePathButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelLink {
            get {
                return ResourceManager.GetString("CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes ({0}) 的本地化字符串。
        /// </summary>
        public static string ChangesCountFormat {
            get {
                return ResourceManager.GetString("ChangesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        public static string CloneLink {
            get {
                return ResourceManager.GetString("CloneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment only 的本地化字符串。
        /// </summary>
        public static string CommentOnly {
            get {
                return ResourceManager.GetString("CommentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comments 的本地化字符串。
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare File as Default Action 的本地化字符串。
        /// </summary>
        public static string CompareFileAsDefaultAction {
            get {
                return ResourceManager.GetString("CompareFileAsDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue your review 的本地化字符串。
        /// </summary>
        public static string ContinueYourReview {
            get {
                return ResourceManager.GetString("ContinueYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not connect to github.com 的本地化字符串。
        /// </summary>
        public static string couldNotConnectToGitHubText {
            get {
                return ResourceManager.GetString("couldNotConnectToGitHubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not connect to the server. 的本地化字符串。
        /// </summary>
        public static string couldNotConnectToTheServerText {
            get {
                return ResourceManager.GetString("couldNotConnectToTheServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create an account 的本地化字符串。
        /// </summary>
        public static string CreateAccountLink {
            get {
                return ResourceManager.GetString("CreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create pull request 的本地化字符串。
        /// </summary>
        public static string CreatePullRequest {
            get {
                return ResourceManager.GetString("CreatePullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description (Optional) 的本地化字符串。
        /// </summary>
        public static string DescriptionOptional {
            get {
                return ResourceManager.GetString("DescriptionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don’t have an account?  的本地化字符串。
        /// </summary>
        public static string dontHaveAnAccountText {
            get {
                return ResourceManager.GetString("dontHaveAnAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don’t have GitHub Enterprise?  的本地化字符串。
        /// </summary>
        public static string dontHaveGitHubEnterpriseText {
            get {
                return ResourceManager.GetString("dontHaveGitHubEnterpriseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check your internet connection and try again. 的本地化字符串。
        /// </summary>
        public static string dotComConnectionFailedMessageMessage {
            get {
                return ResourceManager.GetString("dotComConnectionFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The host isn&apos;t available or is not a GitHub Enterprise server. Check the address and try again. 的本地化字符串。
        /// </summary>
        public static string enterpriseConnectingFailedMessage {
            get {
                return ResourceManager.GetString("enterpriseConnectingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub Enterprise server address 的本地化字符串。
        /// </summary>
        public static string enterpriseUrlPromptText {
            get {
                return ResourceManager.GetString("enterpriseUrlPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not copy to the clipboard. Please try again. 的本地化字符串。
        /// </summary>
        public static string Error_FailedToCopyToClipboard {
            get {
                return ResourceManager.GetString("Error_FailedToCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        public static string fileNameText {
            get {
                return ResourceManager.GetString("fileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter branches 的本地化字符串。
        /// </summary>
        public static string filterBranchesText {
            get {
                return ResourceManager.GetString("filterBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search repositories 的本地化字符串。
        /// </summary>
        public static string filterTextPromptText {
            get {
                return ResourceManager.GetString("filterTextPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (forgot your password?) 的本地化字符串。
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fork 的本地化字符串。
        /// </summary>
        public static string ForkNavigationItemText {
            get {
                return ResourceManager.GetString("ForkNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fork Repository 的本地化字符串。
        /// </summary>
        public static string ForkRepository {
            get {
                return ResourceManager.GetString("ForkRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fork the repository 的本地化字符串。
        /// </summary>
        public static string ForkTheRepository {
            get {
                return ResourceManager.GetString("ForkTheRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Started 的本地化字符串。
        /// </summary>
        public static string GetStartedText {
            get {
                return ResourceManager.GetString("GetStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gist created 的本地化字符串。
        /// </summary>
        public static string gistCreatedMessage {
            get {
                return ResourceManager.GetString("gistCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create gist 的本地化字符串。
        /// </summary>
        public static string gistCreationFailedMessage {
            get {
                return ResourceManager.GetString("gistCreationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect… 的本地化字符串。
        /// </summary>
        public static string GitHubInvitationSectionConnectLabel {
            get {
                return ResourceManager.GetString("GitHubInvitationSectionConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish to GitHub 的本地化字符串。
        /// </summary>
        public static string GitHubPublishSectionTitle {
            get {
                return ResourceManager.GetString("GitHubPublishSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphs 的本地化字符串。
        /// </summary>
        public static string GraphsNavigationItemText {
            get {
                return ResourceManager.GetString("GraphsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Git ignore 的本地化字符串。
        /// </summary>
        public static string ignoreTemplateListText {
            get {
                return ResourceManager.GetString("ignoreTemplateListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issues 的本地化字符串。
        /// </summary>
        public static string IssuesNavigationItemText {
            get {
                return ResourceManager.GetString("IssuesNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learn more 的本地化字符串。
        /// </summary>
        public static string learnMoreLink {
            get {
                return ResourceManager.GetString("learnMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        public static string licenseListText {
            get {
                return ResourceManager.GetString("licenseListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link copied to clipboard 的本地化字符串。
        /// </summary>
        public static string LinkCopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some or all repositories may not have loaded. Close the dialog and try again. 的本地化字符串。
        /// </summary>
        public static string loadingFailedMessageContent {
            get {
                return ResourceManager.GetString("loadingFailedMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while loading repositories 的本地化字符串。
        /// </summary>
        public static string loadingFailedMessageMessage {
            get {
                return ResourceManager.GetString("loadingFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local branch up to date 的本地化字符串。
        /// </summary>
        public static string LocalBranchUpToDate {
            get {
                return ResourceManager.GetString("LocalBranchUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local path 的本地化字符串。
        /// </summary>
        public static string localPathText {
            get {
                return ResourceManager.GetString("localPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check your username and password, then try again 的本地化字符串。
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in failed. 的本地化字符串。
        /// </summary>
        public static string LoginFailedText {
            get {
                return ResourceManager.GetString("LoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in 的本地化字符串。
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private Repository 的本地化字符串。
        /// </summary>
        public static string makePrivateContent {
            get {
                return ResourceManager.GetString("makePrivateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private Gist 的本地化字符串。
        /// </summary>
        public static string makePrivateGist {
            get {
                return ResourceManager.GetString("makePrivateGist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string nameText {
            get {
                return ResourceManager.GetString("nameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Comment 的本地化字符串。
        /// </summary>
        public static string NextComment {
            get {
                return ResourceManager.GetString("NextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No repositories 的本地化字符串。
        /// </summary>
        public static string noRepositoriesMessageText {
            get {
                return ResourceManager.GetString("noRepositoriesMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This repository is not on GitHub 的本地化字符串。
        /// </summary>
        public static string NotAGitHubRepository {
            get {
                return ResourceManager.GetString("NotAGitHubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish this repository to GitHub and get powerful collaboration, code review, and code management for open source and private projects. 的本地化字符串。
        /// </summary>
        public static string NotAGitHubRepositoryMessage {
            get {
                return ResourceManager.GetString("NotAGitHubRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No repository 的本地化字符串。
        /// </summary>
        public static string NotAGitRepository {
            get {
                return ResourceManager.GetString("NotAGitRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We couldn&apos;t find a git repository here. Open a git project or click &quot;File -&gt; Add to Source Control&quot; in a project to get started. 的本地化字符串。
        /// </summary>
        public static string NotAGitRepositoryMessage {
            get {
                return ResourceManager.GetString("NotAGitRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not signed in to {0}, so certain git operations may fail. [Sign in now]({1}) 的本地化字符串。
        /// </summary>
        public static string NotLoggedInMessage {
            get {
                return ResourceManager.GetString("NotLoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File as Default Action 的本地化字符串。
        /// </summary>
        public static string OpenFileAsDefaultAction {
            get {
                return ResourceManager.GetString("OpenFileAsDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File in Solution 的本地化字符串。
        /// </summary>
        public static string OpenFileInSolution {
            get {
                return ResourceManager.GetString("OpenFileInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in Browser 的本地化字符串。
        /// </summary>
        public static string openInBrowser {
            get {
                return ResourceManager.GetString("openInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Pull Request on GitHub 的本地化字符串。
        /// </summary>
        public static string OpenPROnGitHubToolTip {
            get {
                return ResourceManager.GetString("OpenPROnGitHubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the two-factor authentication app on your device to view your authentication code. 的本地化字符串。
        /// </summary>
        public static string openTwoFactorAuthAppText {
            get {
                return ResourceManager.GetString("openTwoFactorAuthAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugging 的本地化字符串。
        /// </summary>
        public static string Options_DebuggingTitle {
            get {
                return ResourceManager.GetString("Options_DebuggingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show PR comments on editor margin 的本地化字符串。
        /// </summary>
        public static string Options_EditorCommentsLabel {
            get {
                return ResourceManager.GetString("Options_EditorCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Trace Logging 的本地化字符串。
        /// </summary>
        public static string Options_EnableTraceLoggingText {
            get {
                return ResourceManager.GetString("Options_EnableTraceLoggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These features might change in a future version 的本地化字符串。
        /// </summary>
        public static string Options_ExperimentalNote {
            get {
                return ResourceManager.GetString("Options_ExperimentalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experimental features 的本地化字符串。
        /// </summary>
        public static string Options_ExperimentalTitle {
            get {
                return ResourceManager.GetString("Options_ExperimentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Fork button in Team Explorer 的本地化字符串。
        /// </summary>
        public static string Options_ForkButtonLabel {
            get {
                return ResourceManager.GetString("Options_ForkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help us improve by sending anonymous usage data 的本地化字符串。
        /// </summary>
        public static string Options_MetricsLabel {
            get {
                return ResourceManager.GetString("Options_MetricsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy 的本地化字符串。
        /// </summary>
        public static string Options_PrivacyTitle {
            get {
                return ResourceManager.GetString("Options_PrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or 的本地化字符串。
        /// </summary>
        public static string orText {
            get {
                return ResourceManager.GetString("orText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outdated comments 的本地化字符串。
        /// </summary>
        public static string OutdatedComments {
            get {
                return ResourceManager.GetString("OutdatedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string pathText {
            get {
                return ResourceManager.GetString("pathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Comment 的本地化字符串。
        /// </summary>
        public static string PreviousComment {
            get {
                return ResourceManager.GetString("PreviousComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 by 的本地化字符串。
        /// </summary>
        public static string prUpdatedByText {
            get {
                return ResourceManager.GetString("prUpdatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated 的本地化字符串。
        /// </summary>
        public static string prUpdatedText {
            get {
                return ResourceManager.GetString("prUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish 的本地化字符串。
        /// </summary>
        public static string publishText {
            get {
                return ResourceManager.GetString("publishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish to GitHub 的本地化字符串。
        /// </summary>
        public static string PublishToGitHubButton {
            get {
                return ResourceManager.GetString("PublishToGitHubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull 的本地化字符串。
        /// </summary>
        public static string Pull {
            get {
                return ResourceManager.GetString("Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pull Requests 的本地化字符串。
        /// </summary>
        public static string PullRequestsNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pulse 的本地化字符串。
        /// </summary>
        public static string PulseNavigationItemText {
            get {
                return ResourceManager.GetString("PulseNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Push 的本地化字符串。
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This repository does not have a remote. Fill out the form to publish it to GitHub. 的本地化字符串。
        /// </summary>
        public static string RepoDoesNotHaveRemoteText {
            get {
                return ResourceManager.GetString("RepoDoesNotHaveRemoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository Name 的本地化字符串。
        /// </summary>
        public static string RepoNameText {
            get {
                return ResourceManager.GetString("RepoNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository created successfully. 的本地化字符串。
        /// </summary>
        public static string RepositoryPublishedMessage {
            get {
                return ResourceManager.GetString("RepositoryPublishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request changes 的本地化字符串。
        /// </summary>
        public static string RequestChanges {
            get {
                return ResourceManager.GetString("RequestChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend 的本地化字符串。
        /// </summary>
        public static string resendCodeButtonContent {
            get {
                return ResourceManager.GetString("resendCodeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send the code to your registered SMS Device again 的本地化字符串。
        /// </summary>
        public static string resendCodeButtonToolTip {
            get {
                return ResourceManager.GetString("resendCodeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reviewers 的本地化字符串。
        /// </summary>
        public static string Reviewers {
            get {
                return ResourceManager.GetString("Reviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in... 的本地化字符串。
        /// </summary>
        public static string SignInCallToAction {
            get {
                return ResourceManager.GetString("SignInCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in 的本地化字符串。
        /// </summary>
        public static string SignInLink {
            get {
                return ResourceManager.GetString("SignInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in to GitHub 的本地化字符串。
        /// </summary>
        public static string SignInToGitHub {
            get {
                return ResourceManager.GetString("SignInToGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign out 的本地化字符串。
        /// </summary>
        public static string SignOutLink {
            get {
                return ResourceManager.GetString("SignOutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign up 的本地化字符串。
        /// </summary>
        public static string SignUpLink {
            get {
                return ResourceManager.GetString("SignUpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start a review 的本地化字符串。
        /// </summary>
        public static string StartAReview {
            get {
                return ResourceManager.GetString("StartAReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit your review for 的本地化字符串。
        /// </summary>
        public static string SubmitYourReviewFor {
            get {
                return ResourceManager.GetString("SubmitYourReviewFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to List View 的本地化字符串。
        /// </summary>
        public static string SwitchToListView {
            get {
                return ResourceManager.GetString("SwitchToListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to Tree View 的本地化字符串。
        /// </summary>
        public static string SwitchToTreeView {
            get {
                return ResourceManager.GetString("SwitchToTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync 的本地化字符串。
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to GitHub for Visual Studio! Why not take a look at our [training](show-training) or [documentation](show-docs)?
        ///
        ///[Don&apos;t show this again](dont-show-again) 的本地化字符串。
        /// </summary>
        public static string TeamExplorerWelcomeMessage {
            get {
                return ResourceManager.GetString("TeamExplorerWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title (required) 的本地化字符串。
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token 的本地化字符串。
        /// </summary>
        public static string TokenPrompt {
            get {
                return ResourceManager.GetString("TokenPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to point to 的本地化字符串。
        /// </summary>
        public static string ToPointTo {
            get {
                return ResourceManager.GetString("ToPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two-factor authentication 的本地化字符串。
        /// </summary>
        public static string twoFactorAuthText {
            get {
                return ResourceManager.GetString("twoFactorAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update comment 的本地化字符串。
        /// </summary>
        public static string UpdateComment {
            get {
                return ResourceManager.GetString("UpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 updated {0} 的本地化字符串。
        /// </summary>
        public static string UpdatedFormat {
            get {
                return ResourceManager.GetString("UpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Update your local repository&apos;s 的本地化字符串。
        /// </summary>
        public static string UpdateYourLocalRepositoryS {
            get {
                return ResourceManager.GetString("UpdateYourLocalRepositoryS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or email 的本地化字符串。
        /// </summary>
        public static string UserNameOrEmailPromptText {
            get {
                return ResourceManager.GetString("UserNameOrEmailPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify 的本地化字符串。
        /// </summary>
        public static string verifyText {
            get {
                return ResourceManager.GetString("verifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Changes 的本地化字符串。
        /// </summary>
        public static string ViewChanges {
            get {
                return ResourceManager.GetString("ViewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Changes in Solution 的本地化字符串。
        /// </summary>
        public static string ViewChangesInSolution {
            get {
                return ResourceManager.GetString("ViewChangesInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View, Checkout or Create a Pull request 的本地化字符串。
        /// </summary>
        public static string ViewCheckoutOrCreateAPullRequest {
            get {
                return ResourceManager.GetString("ViewCheckoutOrCreateAPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View File 的本地化字符串。
        /// </summary>
        public static string ViewFile {
            get {
                return ResourceManager.GetString("ViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wiki 的本地化字符串。
        /// </summary>
        public static string WikiNavigationItemText {
            get {
                return ResourceManager.GetString("WikiNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 wrote 的本地化字符串。
        /// </summary>
        public static string Wrote {
            get {
                return ResourceManager.GetString("Wrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must commit and push your changes to add a comment here. 的本地化字符串。
        /// </summary>
        public static string YouMustCommitAndPushYourChangesToAddACommentHere {
            get {
                return ResourceManager.GetString("YouMustCommitAndPushYourChangesToAddACommentHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your review summary 的本地化字符串。
        /// </summary>
        public static string YourReviewSummary {
            get {
                return ResourceManager.GetString("YourReviewSummary", resourceCulture);
            }
        }
    }
}
