// <auto-generated/>

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("GitHub.VisualStudio")]
[assembly: AssemblyVersionAttribute(AssemblyVersionInformation.Version)]
[assembly: AssemblyFileVersionAttribute(AssemblyVersionInformation.Version)]
[assembly: ComVisibleAttribute(false)]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.0.1";
    }
}
