//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHub.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddedFileStatus {
            get {
                return ResourceManager.GetString("AddedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review comment.
        /// </summary>
        public static string AddReviewComment {
            get {
                return ResourceManager.GetString("AddReviewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a single comment.
        /// </summary>
        public static string AddSingleComment {
            get {
                return ResourceManager.GetString("AddSingleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your review.
        /// </summary>
        public static string AddYourReview {
            get {
                return ResourceManager.GetString("AddYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        public static string Assignee {
            get {
                return ResourceManager.GetString("Assignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication code.
        /// </summary>
        public static string authenticationFailedLabelContent {
            get {
                return ResourceManager.GetString("authenticationFailedLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try entering the code again or clicking the resend button to get a new authentication code..
        /// </summary>
        public static string authenticationFailedLabelMessage {
            get {
                return ResourceManager.GetString("authenticationFailedLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication code sent!.
        /// </summary>
        public static string authenticationSentLabelContent {
            get {
                return ResourceManager.GetString("authenticationSentLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not receive the authentication code, contact support@github.com..
        /// </summary>
        public static string authenticationSentLabelMessage {
            get {
                return ResourceManager.GetString("authenticationSentLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GitHub extension is not available inside Blend.
        /// </summary>
        public static string BlendDialogText {
            get {
                return ResourceManager.GetString("BlendDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful collaboration, code review, and code management for open source and private projects..
        /// </summary>
        public static string BlurbText {
            get {
                return ResourceManager.GetString("BlurbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a containing folder for your new repository..
        /// </summary>
        public static string BrowseForDirectory {
            get {
                return ResourceManager.GetString("BrowseForDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string browsePathButtonContent {
            get {
                return ResourceManager.GetString("browsePathButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLink {
            get {
                return ResourceManager.GetString("CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this review? You will lose all your pending comments..
        /// </summary>
        public static string CancelPendingReviewConfirmation {
            get {
                return ResourceManager.GetString("CancelPendingReviewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Review.
        /// </summary>
        public static string CancelPendingReviewConfirmationCaption {
            get {
                return ResourceManager.GetString("CancelPendingReviewConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a directory at this location, but it doesn&apos;t contain a repository..
        /// </summary>
        public static string CantFindARepositoryAtLocalPath {
            get {
                return ResourceManager.GetString("CantFindARepositoryAtLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find GitHub URL for repository.
        /// </summary>
        public static string CantFindGitHubUrlForRepository {
            get {
                return ResourceManager.GetString("CantFindGitHubUrlForRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes ({0}).
        /// </summary>
        public static string ChangesCountFormat {
            get {
                return ResourceManager.GetString("ChangesCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working file is different to the file at &apos;{0}&apos;. Please checkout the corresponding branch, pull request or commit..
        /// </summary>
        public static string ChangesInWorkingDirectoryMessage {
            get {
                return ResourceManager.GetString("ChangesInWorkingDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes Requested.
        /// </summary>
        public static string ChangesRequested {
            get {
                return ResourceManager.GetString("ChangesRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string CloneLink {
            get {
                return ResourceManager.GetString("CloneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone a Repository.
        /// </summary>
        public static string CloneTitle {
            get {
                return ResourceManager.GetString("CloneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented.
        /// </summary>
        public static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment only.
        /// </summary>
        public static string CommentOnly {
            get {
                return ResourceManager.GetString("CommentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare File as Default Action.
        /// </summary>
        public static string CompareFileAsDefaultAction {
            get {
                return ResourceManager.GetString("CompareFileAsDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue your review.
        /// </summary>
        public static string ContinueYourReview {
            get {
                return ResourceManager.GetString("ContinueYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to github.com.
        /// </summary>
        public static string CouldNotConnectToGitHub {
            get {
                return ResourceManager.GetString("CouldNotConnectToGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to github.com.
        /// </summary>
        public static string couldNotConnectToGitHubText {
            get {
                return ResourceManager.GetString("couldNotConnectToGitHubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server..
        /// </summary>
        public static string couldNotConnectToTheServerText {
            get {
                return ResourceManager.GetString("couldNotConnectToTheServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find file corresponding to &apos;{0}&apos; in the repository. Please do a &apos;git fetch&apos; or checkout the target pull request..
        /// </summary>
        public static string CouldntFindCorrespondingFile {
            get {
                return ResourceManager.GetString("CouldntFindCorrespondingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Git.exe on PATH.
        ///
        ///Please install Git for Windows from:
        ///https://git-scm.com/download/win.
        /// </summary>
        public static string CouldntFindGitOnPath {
            get {
                return ResourceManager.GetString("CouldntFindGitOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string CreateAccountLink {
            get {
                return ResourceManager.GetString("CreateAccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a pull request.
        /// </summary>
        public static string CreateAPullRequest {
            get {
                return ResourceManager.GetString("CreateAPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a GitHub Gist.
        /// </summary>
        public static string CreateGistTitle {
            get {
                return ResourceManager.GetString("CreateGistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create pull request.
        /// </summary>
        public static string CreatePullRequest {
            get {
                return ResourceManager.GetString("CreatePullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a {0} Repository.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} day ago.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} days ago.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GistFromVisualStudio.cs.
        /// </summary>
        public static string DefaultGistFileName {
            get {
                return ResourceManager.GetString("DefaultGistFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        public static string DeleteCommentConfirmation {
            get {
                return ResourceManager.GetString("DeleteCommentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Comment.
        /// </summary>
        public static string DeleteCommentConfirmationCaption {
            get {
                return ResourceManager.GetString("DeleteCommentConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Optional).
        /// </summary>
        public static string DescriptionOptional {
            get {
                return ResourceManager.GetString("DescriptionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file exists at the destination path..
        /// </summary>
        public static string DestinationAlreadyExists {
            get {
                return ResourceManager.GetString("DestinationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open the repository &apos;{0}&apos; and try again.
        /// </summary>
        public static string DifferentRepositoryMessage {
            get {
                return ResourceManager.GetString("DifferentRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have an account? .
        /// </summary>
        public static string dontHaveAnAccountText {
            get {
                return ResourceManager.GetString("dontHaveAnAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don’t have GitHub Enterprise? .
        /// </summary>
        public static string dontHaveGitHubEnterpriseText {
            get {
                return ResourceManager.GetString("dontHaveGitHubEnterpriseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again..
        /// </summary>
        public static string dotComConnectionFailedMessageMessage {
            get {
                return ResourceManager.GetString("dotComConnectionFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host isn&apos;t available or is not a GitHub Enterprise server. Check the address and try again..
        /// </summary>
        public static string enterpriseConnectingFailedMessage {
            get {
                return ResourceManager.GetString("enterpriseConnectingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Enterprise server address.
        /// </summary>
        public static string enterpriseUrlPromptText {
            get {
                return ResourceManager.GetString("enterpriseUrlPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an Enterprise URL.
        /// </summary>
        public static string EnterpriseUrlValidatorEmpty {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Enterprise URL.
        /// </summary>
        public static string EnterpriseUrlValidatorInvalid {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Enterprise server. Please enter an Enterprise URL.
        /// </summary>
        public static string EnterpriseUrlValidatorNotAGitHubHost {
            get {
                return ResourceManager.GetString("EnterpriseUrlValidatorNotAGitHubHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not copy to the clipboard. Please try again..
        /// </summary>
        public static string Error_FailedToCopyToClipboard {
            get {
                return ResourceManager.GetString("Error_FailedToCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string fileNameText {
            get {
                return ResourceManager.GetString("fileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter branches.
        /// </summary>
        public static string filterBranchesText {
            get {
                return ResourceManager.GetString("filterBranchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Author.
        /// </summary>
        public static string FilterByAuthor {
            get {
                return ResourceManager.GetString("FilterByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search repositories.
        /// </summary>
        public static string filterTextPromptText {
            get {
                return ResourceManager.GetString("filterTextPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (forgot your password?).
        /// </summary>
        public static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fork.
        /// </summary>
        public static string Fork {
            get {
                return ResourceManager.GetString("Fork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork.
        /// </summary>
        public static string ForkNavigationItemText {
            get {
                return ResourceManager.GetString("ForkNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork Repository.
        /// </summary>
        public static string ForkRepository {
            get {
                return ResourceManager.GetString("ForkRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork Repository.
        /// </summary>
        public static string ForkRepositoryTitle {
            get {
                return ResourceManager.GetString("ForkRepositoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork the repository.
        /// </summary>
        public static string ForkTheRepository {
            get {
                return ResourceManager.GetString("ForkTheRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStartedText {
            get {
                return ResourceManager.GetString("GetStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gist created.
        /// </summary>
        public static string gistCreatedMessage {
            get {
                return ResourceManager.GetString("gistCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create gist.
        /// </summary>
        public static string gistCreationFailedMessage {
            get {
                return ResourceManager.GetString("gistCreationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect….
        /// </summary>
        public static string GitHubInvitationSectionConnectLabel {
            get {
                return ResourceManager.GetString("GitHubInvitationSectionConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to GitHub.
        /// </summary>
        public static string GitHubPublishSectionTitle {
            get {
                return ResourceManager.GetString("GitHubPublishSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string GraphsNavigationItemText {
            get {
                return ResourceManager.GetString("GraphsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} hour ago.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} hours ago.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git ignore.
        /// </summary>
        public static string ignoreTemplateListText {
            get {
                return ResourceManager.GetString("ignoreTemplateListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [invalid].
        /// </summary>
        public static string InvalidBranchName {
            get {
                return ResourceManager.GetString("InvalidBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        public static string IssuesNavigationItemText {
            get {
                return ResourceManager.GetString("IssuesNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string learnMoreLink {
            get {
                return ResourceManager.GetString("learnMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string licenseListText {
            get {
                return ResourceManager.GetString("licenseListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied to clipboard.
        /// </summary>
        public static string LinkCopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("LinkCopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some or all repositories may not have loaded. Close the dialog and try again..
        /// </summary>
        public static string loadingFailedMessageContent {
            get {
                return ResourceManager.GetString("loadingFailedMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading repositories.
        /// </summary>
        public static string loadingFailedMessageMessage {
            get {
                return ResourceManager.GetString("loadingFailedMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local branch up to date.
        /// </summary>
        public static string LocalBranchUpToDate {
            get {
                return ResourceManager.GetString("LocalBranchUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path.
        /// </summary>
        public static string localPathText {
            get {
                return ResourceManager.GetString("localPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A repository already exists at this location, but it doesn&apos;t have a remote named &quot;origin&quot;..
        /// </summary>
        public static string LocalRepositoryDoesntHaveARemoteOrigin {
            get {
                return ResourceManager.GetString("LocalRepositoryDoesntHaveARemoteOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A repository already exists at this location, but it has a remote of {0}..
        /// </summary>
        public static string LocalRepositoryHasARemoteOf {
            get {
                return ResourceManager.GetString("LocalRepositoryHasARemoteOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to use your password and not a Personal Access token to sign in..
        /// </summary>
        public static string LoginFailedForbiddenMessage {
            get {
                return ResourceManager.GetString("LoginFailedForbiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username and password, then try again.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed..
        /// </summary>
        public static string LoginFailedText {
            get {
                return ResourceManager.GetString("LoginFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To GitHub.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Required.
        /// </summary>
        public static string LogoutRequired {
            get {
                return ResourceManager.GetString("LogoutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Repository.
        /// </summary>
        public static string makePrivateContent {
            get {
                return ResourceManager.GetString("makePrivateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Gist.
        /// </summary>
        public static string makePrivateGist {
            get {
                return ResourceManager.GetString("makePrivateGist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} minute ago.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} minutes ago.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} month ago.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} months ago.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} most recently pushed.
        /// </summary>
        public static string MostRecentlyPushed {
            get {
                return ResourceManager.GetString("MostRecentlyPushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pull before you can push.
        /// </summary>
        public static string MustPullBeforePush {
            get {
                return ResourceManager.GetString("MustPullBeforePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nameText {
            get {
                return ResourceManager.GetString("nameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout PR branch before navigating to Editor.
        /// </summary>
        public static string NavigateToEditorNotCheckedOutInfoMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorNotCheckedOutInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to navigate to Editor (PR branch must be checked out).
        /// </summary>
        public static string NavigateToEditorNotCheckedOutStatusMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorNotCheckedOutStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to navigate to Editor.
        /// </summary>
        public static string NavigateToEditorStatusMessage {
            get {
                return ResourceManager.GetString("NavigateToEditorStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Comment.
        /// </summary>
        public static string NextComment {
            get {
                return ResourceManager.GetString("NextComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active repository to navigate.
        /// </summary>
        public static string NoActiveRepositoryMessage {
            get {
                return ResourceManager.GetString("NoActiveRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commits to pull.
        /// </summary>
        public static string NoCommitsToPull {
            get {
                return ResourceManager.GetString("NoCommitsToPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commits to push.
        /// </summary>
        public static string NoCommitsToPush {
            get {
                return ResourceManager.GetString("NoCommitsToPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *No description provided.*.
        /// </summary>
        public static string NoDescriptionProvidedMarkdown {
            get {
                return ResourceManager.GetString("NoDescriptionProvidedMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t a find a GitHub URL in clipboard.
        /// </summary>
        public static string NoGitHubUrlMessage {
            get {
                return ResourceManager.GetString("NoGitHubUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repositories.
        /// </summary>
        public static string noRepositoriesMessageText {
            get {
                return ResourceManager.GetString("noRepositoriesMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target URL has a different owner to the current repository..
        /// </summary>
        public static string NoResolveDifferentOwnerMessage {
            get {
                return ResourceManager.GetString("NoResolveDifferentOwnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find target URL in current repository. Try again after doing a fetch..
        /// </summary>
        public static string NoResolveSameOwnerMessage {
            get {
                return ResourceManager.GetString("NoResolveSameOwnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results matched your search..
        /// </summary>
        public static string NoResultsMatchedYourSearch {
            get {
                return ResourceManager.GetString("NoResultsMatchedYourSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This repository is not on GitHub.
        /// </summary>
        public static string NotAGitHubRepository {
            get {
                return ResourceManager.GetString("NotAGitHubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish this repository to GitHub and get powerful collaboration, code review, and code management for open source and private projects..
        /// </summary>
        public static string NotAGitHubRepositoryMessage {
            get {
                return ResourceManager.GetString("NotAGitHubRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository.
        /// </summary>
        public static string NotAGitRepository {
            get {
                return ResourceManager.GetString("NotAGitRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find a git repository here. Open a git project or click &quot;File -&gt; Add to Source Control&quot; in a project to get started..
        /// </summary>
        public static string NotAGitRepositoryMessage {
            get {
                return ResourceManager.GetString("NotAGitRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in to {0}, so certain git operations may fail. [Sign in now]({1}).
        /// </summary>
        public static string NotLoggedInMessage {
            get {
                return ResourceManager.GetString("NotLoggedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File as Default Action.
        /// </summary>
        public static string OpenFileAsDefaultAction {
            get {
                return ResourceManager.GetString("OpenFileAsDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File in Solution.
        /// </summary>
        public static string OpenFileInSolution {
            get {
                return ResourceManager.GetString("OpenFileInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from GitHub.
        /// </summary>
        public static string OpenFromGitHubTitle {
            get {
                return ResourceManager.GetString("OpenFromGitHubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string openInBrowser {
            get {
                return ResourceManager.GetString("openInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Pull Request on GitHub.
        /// </summary>
        public static string OpenPROnGitHubToolTip {
            get {
                return ResourceManager.GetString("OpenPROnGitHubToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open repository at &apos;{0}&apos;?.
        /// </summary>
        public static string OpenRepositoryAtDir {
            get {
                return ResourceManager.GetString("OpenRepositoryAtDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the two-factor authentication app on your device to view your authentication code..
        /// </summary>
        public static string openTwoFactorAuthAppText {
            get {
                return ResourceManager.GetString("openTwoFactorAuthAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string Options_DebuggingTitle {
            get {
                return ResourceManager.GetString("Options_DebuggingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PR comments on editor margin.
        /// </summary>
        public static string Options_EditorCommentsLabel {
            get {
                return ResourceManager.GetString("Options_EditorCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Trace Logging.
        /// </summary>
        public static string Options_EnableTraceLoggingText {
            get {
                return ResourceManager.GetString("Options_EnableTraceLoggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These features might change in a future version.
        /// </summary>
        public static string Options_ExperimentalNote {
            get {
                return ResourceManager.GetString("Options_ExperimentalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental features.
        /// </summary>
        public static string Options_ExperimentalTitle {
            get {
                return ResourceManager.GetString("Options_ExperimentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve by sending anonymous usage data.
        /// </summary>
        public static string Options_MetricsLabel {
            get {
                return ResourceManager.GetString("Options_MetricsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Options_PrivacyTitle {
            get {
                return ResourceManager.GetString("Options_PrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string orText {
            get {
                return ResourceManager.GetString("orText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated comments.
        /// </summary>
        public static string OutdatedComments {
            get {
                return ResourceManager.GetString("OutdatedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string PasswordValidatorEmpty {
            get {
                return ResourceManager.GetString("PasswordValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string pathText {
            get {
                return ResourceManager.GetString("pathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request for branch **{0}** created successfully at [{1}]({2}).
        /// </summary>
        public static string PRCreatedUpstream {
            get {
                return ResourceManager.GetString("PRCreatedUpstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Comment.
        /// </summary>
        public static string PreviousComment {
            get {
                return ResourceManager.GetString("PreviousComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string prUpdatedByText {
            get {
                return ResourceManager.GetString("prUpdatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string prUpdatedText {
            get {
                return ResourceManager.GetString("prUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string publishText {
            get {
                return ResourceManager.GetString("publishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish repository.
        /// </summary>
        public static string PublishTitle {
            get {
                return ResourceManager.GetString("PublishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to GitHub.
        /// </summary>
        public static string PublishToGitHubButton {
            get {
                return ResourceManager.GetString("PublishToGitHubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish repository to {0}.
        /// </summary>
        public static string PublishToTitle {
            get {
                return ResourceManager.GetString("PublishToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string Pull {
            get {
                return ResourceManager.GetString("Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title for the Pull Request.
        /// </summary>
        public static string PullRequestCreationTitleValidatorEmpty {
            get {
                return ResourceManager.GetString("PullRequestCreationTitleValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout {0}.
        /// </summary>
        public static string PullRequestDetailsCheckout {
            get {
                return ResourceManager.GetString("PullRequestDetailsCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout to {0}.
        /// </summary>
        public static string PullRequestDetailsCheckoutTo {
            get {
                return ResourceManager.GetString("PullRequestDetailsCheckoutTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull from {0} branch {1}.
        /// </summary>
        public static string PullRequestDetailsPullToolTip {
            get {
                return ResourceManager.GetString("PullRequestDetailsPullToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to {0} branch {1}.
        /// </summary>
        public static string PullRequestDetailsPushToolTip {
            get {
                return ResourceManager.GetString("PullRequestDetailsPushToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request.
        /// </summary>
        public static string PullRequestNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull requests let you tell others about changes you&apos;ve pushed to a repository on GitHub.
        /// </summary>
        public static string PullRequestsLetYouTellOthersAboutChangesYouVePushedToARepositoryOnGitHub {
            get {
                return ResourceManager.GetString("PullRequestsLetYouTellOthersAboutChangesYouVePushedToARepositoryOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests.
        /// </summary>
        public static string PullRequestsNavigationItemText {
            get {
                return ResourceManager.GetString("PullRequestsNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target branch cannot be the same.
        /// </summary>
        public static string PullRequestSourceAndTargetBranchTheSame {
            get {
                return ResourceManager.GetString("PullRequestSourceAndTargetBranchTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source branch doesn&apos;t exist remotely, have you pushed it?.
        /// </summary>
        public static string PullRequestSourceBranchDoesNotExist {
            get {
                return ResourceManager.GetString("PullRequestSourceBranchDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string PulseNavigationItemText {
            get {
                return ResourceManager.GetString("PulseNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string RenamedFileStatus {
            get {
                return ResourceManager.GetString("RenamedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This repository does not have a remote. Fill out the form to publish it to GitHub..
        /// </summary>
        public static string RepoDoesNotHaveRemoteText {
            get {
                return ResourceManager.GetString("RepoDoesNotHaveRemoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Name.
        /// </summary>
        public static string RepoNameText {
            get {
                return ResourceManager.GetString("RepoNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories must have a remote called &quot;origin&quot; defined in order to locate their GitHub URL..
        /// </summary>
        public static string RepositoriesMustHaveRemoteOrigin {
            get {
                return ResourceManager.GetString("RepositoriesMustHaveRemoteOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rename one of your existing remotes to &apos;origin&apos; or add a new remote named &apos;origin&apos; and fetch. This can be done from the command line or by clicking the button below..
        /// </summary>
        public static string RepositoriesMustHaveRemoteOriginHowToFix {
            get {
                return ResourceManager.GetString("RepositoriesMustHaveRemoteOriginHowToFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected repository..
        /// </summary>
        public static string RepositoryCloneFailedNoSelectedRepo {
            get {
                return ResourceManager.GetString("RepositoryCloneFailedNoSelectedRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a repository path.
        /// </summary>
        public static string RepositoryCreationClonePathEmpty {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid path.
        /// </summary>
        public static string RepositoryCreationClonePathInvalid {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path contains invalid characters.
        /// </summary>
        public static string RepositoryCreationClonePathInvalidCharacters {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long.
        /// </summary>
        public static string RepositoryCreationClonePathTooLong {
            get {
                return ResourceManager.GetString("RepositoryCreationClonePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository &apos;{0}/{1}&apos; already exists..
        /// </summary>
        public static string RepositoryCreationFailedAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the repository name or select a different account and try again..
        /// </summary>
        public static string RepositoryCreationFailedAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded private repositories quota..
        /// </summary>
        public static string RepositoryCreationFailedQuota {
            get {
                return ResourceManager.GetString("RepositoryCreationFailedQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository with same name already exists at this location.
        /// </summary>
        public static string RepositoryNameValidatorAlreadyExists {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a repository name.
        /// </summary>
        public static string RepositoryNameValidatorEmpty {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name must be fewer than 100 characters.
        /// </summary>
        public static string RepositoryNameValidatorTooLong {
            get {
                return ResourceManager.GetString("RepositoryNameValidatorTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository created successfully..
        /// </summary>
        public static string RepositoryPublishedMessage {
            get {
                return ResourceManager.GetString("RepositoryPublishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request changes.
        /// </summary>
        public static string RequestChanges {
            get {
                return ResourceManager.GetString("RequestChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string resendCodeButtonContent {
            get {
                return ResourceManager.GetString("resendCodeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the code to your registered SMS Device again.
        /// </summary>
        public static string resendCodeButtonToolTip {
            get {
                return ResourceManager.GetString("resendCodeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewers.
        /// </summary>
        public static string Reviewers {
            get {
                return ResourceManager.GetString("Reviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be created as {0}.
        /// </summary>
        public static string SafeRepositoryNameWarning {
            get {
                return ResourceManager.GetString("SafeRepositoryNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} second ago.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} seconds ago.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Fork.
        /// </summary>
        public static string SelectFork {
            get {
                return ResourceManager.GetString("SelectFork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in....
        /// </summary>
        public static string SignInCallToAction {
            get {
                return ResourceManager.GetString("SignInCallToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInLink {
            get {
                return ResourceManager.GetString("SignInLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to GitHub.
        /// </summary>
        public static string SignInToGitHub {
            get {
                return ResourceManager.GetString("SignInToGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with your browser.
        /// </summary>
        public static string SignInWithYourBrowser {
            get {
                return ResourceManager.GetString("SignInWithYourBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutLink {
            get {
                return ResourceManager.GetString("SignOutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpLink {
            get {
                return ResourceManager.GetString("SignUpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source repository is no longer available..
        /// </summary>
        public static string SourceRepositoryNoLongerAvailable {
            get {
                return ResourceManager.GetString("SourceRepositoryNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a review.
        /// </summary>
        public static string StartAReview {
            get {
                return ResourceManager.GetString("StartAReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your review for.
        /// </summary>
        public static string SubmitYourReviewFor {
            get {
                return ResourceManager.GetString("SubmitYourReviewFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Origin.
        /// </summary>
        public static string SwitchOriginTitle {
            get {
                return ResourceManager.GetString("SwitchOriginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to List View.
        /// </summary>
        public static string SwitchToListView {
            get {
                return ResourceManager.GetString("SwitchToListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Tree View.
        /// </summary>
        public static string SwitchToTreeView {
            get {
                return ResourceManager.GetString("SwitchToTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync {0} submodules.
        /// </summary>
        public static string SyncSubmodules {
            get {
                return ResourceManager.GetString("SyncSubmodules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to GitHub for Visual Studio! Why not take a look at our [training](show-training) or [documentation](show-docs)?
        ///
        ///[Don&apos;t show this again](dont-show-again).
        /// </summary>
        public static string TeamExplorerWelcomeMessage {
            get {
                return ResourceManager.GetString("TeamExplorerWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any open pull requests.
        /// </summary>
        public static string ThereArenTAnyOpenPullRequests {
            get {
                return ResourceManager.GetString("ThereArenTAnyOpenPullRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (required).
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started you can.
        /// </summary>
        public static string ToGetStartedYouCan {
            get {
                return ResourceManager.GetString("ToGetStartedYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string TokenPrompt {
            get {
                return ResourceManager.GetString("TokenPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to point to.
        /// </summary>
        public static string ToPointTo {
            get {
                return ResourceManager.GetString("ToPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the two-factor authentication app on your device to view your authentication code..
        /// </summary>
        public static string TwoFactorApp {
            get {
                return ResourceManager.GetString("TwoFactorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string twoFactorAuthText {
            get {
                return ResourceManager.GetString("twoFactorAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent you a message via SMS with your authentication code..
        /// </summary>
        public static string TwoFactorSms {
            get {
                return ResourceManager.GetString("TwoFactorSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor authentication required.
        /// </summary>
        public static string TwoFactorTitle {
            get {
                return ResourceManager.GetString("TwoFactorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a sign in authentication code here.
        /// </summary>
        public static string TwoFactorUnknown {
            get {
                return ResourceManager.GetString("TwoFactorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open from &apos;{0}&apos;. Only URLs that link to repository files are currently supported..
        /// </summary>
        public static string UnknownLinkTypeMessage {
            get {
                return ResourceManager.GetString("UnknownLinkTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update comment.
        /// </summary>
        public static string UpdateComment {
            get {
                return ResourceManager.GetString("UpdateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated {0}.
        /// </summary>
        public static string UpdatedFormat {
            get {
                return ResourceManager.GetString("UpdatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update your local repository&apos;s.
        /// </summary>
        public static string UpdateYourLocalRepositoryS {
            get {
                return ResourceManager.GetString("UpdateYourLocalRepositoryS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email.
        /// </summary>
        public static string UserNameOrEmailPromptText {
            get {
                return ResourceManager.GetString("UserNameOrEmailPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username or email address.
        /// </summary>
        public static string UsernameOrEmailValidatorEmpty {
            get {
                return ResourceManager.GetString("UsernameOrEmailValidatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email address must not have spaces.
        /// </summary>
        public static string UsernameOrEmailValidatorSpaces {
            get {
                return ResourceManager.GetString("UsernameOrEmailValidatorSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string verifyText {
            get {
                return ResourceManager.GetString("verifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changes.
        /// </summary>
        public static string ViewChanges {
            get {
                return ResourceManager.GetString("ViewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Changes in Solution.
        /// </summary>
        public static string ViewChangesInSolution {
            get {
                return ResourceManager.GetString("ViewChangesInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Checkout or Create a Pull request.
        /// </summary>
        public static string ViewCheckoutOrCreateAPullRequest {
            get {
                return ResourceManager.GetString("ViewCheckoutOrCreateAPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View File.
        /// </summary>
        public static string ViewFile {
            get {
                return ResourceManager.GetString("ViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string WikiNavigationItemText {
            get {
                return ResourceManager.GetString("WikiNavigationItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot checkout as your working directory has uncommitted changes..
        /// </summary>
        public static string WorkingDirectoryHasUncommittedCHanges {
            get {
                return ResourceManager.GetString("WorkingDirectoryHasUncommittedCHanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrote.
        /// </summary>
        public static string Wrote {
            get {
                return ResourceManager.GetString("Wrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} year ago.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} years ago.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already cloned to this location. Click &apos;Open&apos; to open the local repository..
        /// </summary>
        public static string YouHaveAlreadyClonedToThisLocation {
            get {
                return ResourceManager.GetString("YouHaveAlreadyClonedToThisLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must commit and push your changes to add a comment here..
        /// </summary>
        public static string YouMustCommitAndPushYourChangesToAddACommentHere {
            get {
                return ResourceManager.GetString("YouMustCommitAndPushYourChangesToAddACommentHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your review summary.
        /// </summary>
        public static string YourReviewSummary {
            get {
                return ResourceManager.GetString("YourReviewSummary", resourceCulture);
            }
        }
    }
}
